FROM ubuntu:14.04

MAINTAINER Paulo Pires <pjpires@gmail.com>

RUN echo "deb http://archive.ubuntu.com/ubuntu trusty main universe" > /etc/apt/sources.list && \
    apt-get update && \
    apt-get upgrade -y

# Install Oracle JRE 8
RUN apt-get -y install software-properties-common && \
    add-apt-repository ppa:webupd8team/java && \
    apt-get -y update && \
    echo "oracle-java8-installer  shared/accepted-oracle-license-v1-1 boolean true" | debconf-set-selections && \
    apt-get -y install oracle-java8-installer maven git && \
    apt-get install oracle-java8-set-default && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/oracle-jdk8-installer
    
    