:icons: font

////
* Write changelog entries in present tense
* Include GitHub issue or PR if possible using link:http://...[#123] format
* Review your changelog entries
* Don't include security sensitive information in the changelog
* Include links to documentation if possible
////

= Gentics Mesh Changelog

[[v0.22.8]]
== 0.22.8 (30.11.2018)

icon:plus[] OrientDB: The included OrientDB version has been updated to version 2.2.37

[[v0.22.7]]
== 0.22.7 (12.11.2018)

icon:check[] Elasticsearch: The check for the `ingest-attachment` plugin was fixed for installations which were using the `AWS` Elasticsearch service.

icon:plus[] API: Make OAuth2 Server options overrideable via environment variables.

[[v0.22.6]]
== 0.22.6 (30.10.2018)

icon:check[] Java REST Client: Fixed wrong log output information.

icon:check[] REST: Fixed error while fetching jobs for deleted projects.

icon:plus[] Elasticsearch: The index sync will now automatically remove no longer used indices.


[[v0.22.5]]
== 0.22.5 (12.10.2018)

icon:plus[] A default paging value can now be configured via the `defaultPageSize` field in the `mesh.yml` file, or the `MESH_DEFAULT_PAGE_SIZE` environment variable.

icon:check[] Java REST Client: Add more detailed error information to `MeshRestClientMessageException` class.

[[v0.22.4]]
== 0.22.4 (08.10.2018)

icon:check[] REST: The response error code handling for uploads has been updated. Previously no error 413 was returned when the upload limit was reached.

icon:check[] Elasticsearch: The initial sync check will be omitted if no elasticsearch has been configured.

icon:plus[] Plugins: It is now possible to override plugin config in a `config.local.yml` file.

[[v0.22.3]]
== 0.22.3 (20.09.2018)

icon:plus[] It is now possible to add custom languages by configuration.

[[v0.22.2]]
== 0.22.2 (13.09.2018)

icon:check[] Java REST Client: fixed a bug that could lead to duplicate request headers

[[v0.22.1]]
== 0.22.1 (14.08.2018)

icon:plus[] Migration: The micronode and release migration performance has been greatly enhanced.

[[v0.22.0]]
== 0.22.0 (19.07.2018)

icon:bullhorn[] Metadata extraction

[quote]
____
This version of Gentics Mesh introduces the __Metadata extraction__ of file uploads (PDF, Images).
GPS information of images will now be added to the search index. That information can be used to run link:https://getmesh.io/docs/beta/elasticsearch.html#_search_nodes_by_geolocation_of_images[geo search queries].
A detailed description of this feature can be found in our https://getmesh.io/docs/beta/features.html#_metadata_handling[File Uploads Documentation].

Existing binary fields will not be automatically be processed to provide the metadata. You need to manually re-upload the data in order to generate the metadata properties.
____

icon:check[] Image: Focal point information within binary fields will now be utilized when invoking a download request which contains `?crop=fp&height=200&width=100`. Previously the stored information was not used and no focal point cropping was executed. link:https://github.com/gentics/mesh/issues/417[#417]

icon:check[] Schema: A minor issue within the schema diff mechanism has been fixed. Previously the `elasticsearch` property was not correctly handled if an empty object has been provided during an update.

[[v0.21.5]]
== 0.21.5 (14.07.2018)

icon:check[] REST: The order of elements within a micronode list field will now be correctly preserved. Previously the order would change once the list reached a size of about 20 elements. link:https://github.com/gentics/mesh/issues/469[#469]

icon:check[] Memory: The memory footprint for deletion, publish and unpublish operations has been greatly reduced.

icon:check[] Config: Fixed handling of `MESH_VERTX_WORKER_POOL_SIZE` and `MESH_VERTX_EVENT_POOL_SIZE` environment variables. These variables were previously ignored.

icon:plus[] REST: The amount of fields which will be returned can now be tuned using the `?fields` query parameter. The parameter can be used to improve the write performance by only including the `uuid` parameter in the response. 

icon:check[] REST: The node update response will now contain the updated node in the correct language. Any provided language parameter will be ignored.

[[v0.21.4]]
== 0.21.4 (09.07.2018)

icon:plus[] Migration: Segment path conflicts will now automatically be resolved during the node migration. Information about actions taken can be found within the response of the job migration.

icon:plus[] Migration: The node migration performance has been greatly enhanced. link:https://github.com/gentics/mesh/issues/453[#453]

icon:check[] Elasticsearch: Start up of Gentics Mesh will now fail early if the embedded Elasticsearch server can't be started. link:https://github.com/gentics/mesh/issues/445[#445]

icon:check[] Elasticsearch: The error logging has been enhanced. More detailed information will be logged if an index can't be created.

icon:check[] UI: Fixed potential encoding issues in the UI on systems which are not using the UTF-8 default character set.

icon:check[] Core: Fixed a bug that caused an unwanted schema migration when a schema update without any changes was invoked. This was the case with the `elasticsearch` properties.

[[v0.21.3]]
== 0.21.3 (19.06.2018)

icon:check[] GraphQL: Fixed a bug that caused an error when multiple queries where executed concurrently.

icon:check[] GraphQL: The language fallback handling for node reference fields has been enhanced. The language of the node will now be utilized when no language fallback has been specified.

icon:check[] GraphQL: The language fallback handling has been enhanced. The language fallback will now automatically be passed along to load nested fields.

icon:check[] GraphQL: The link resolving of html and string fields has been updated. Previously the language of the node which contained the field was not taken into account while resolving mesh links in these fields.

[[v0.21.2]]
== 0.21.2 (13.06.2018)

icon:check[] Elasticsearch: A compatibility issue with Elasticsearch instances which were hosted on Amazon AWS has been fixed. Previously the check for installed ES plugins failed.

[[v0.21.1]]
== 0.21.1 (28.05.2018)

icon:plus[] Elasticsearch: It is now possible to configure custom mappings for binary fields. Currently only the `mimeType` and `file.content` fields can be mapped. An example for this mapping can be found in the documentation.

[[v0.21.0]]
== 0.21.0 (27.05.2018)

icon:bullhorn[] Binary Search

[quote]
____
This version of Gentics Mesh introduces the __Binary Search support__.

The https://www.elastic.co/guide/en/elasticsearch/plugins/6.2/ingest-attachment.html[Elasticsearch Ingest Attachment Plugin] will be utilized if possible to process text file uploads (PDF, DOC, DOCX).
A detailed description of this feature can be found in our https://getmesh.io/docs/beta/elasticsearch.html#_binarysearch[Elasticsearch Documentation].
____

icon:plus[] Elasticsearch: It is now possible to configure a prefix string within the search options. Multiple Gentics Mesh installations with different prefixes can now utilize the same Elasticsearch server. Created indices and pipelines will automatically be prefixed. Other elements which do not start with the prefix will be ignored.

[[v0.20.0]]
== 0.20.0 (25.05.2018)

icon:bullhorn[] OAuth2 Support

[quote]
____
This version of Gentics Mesh introduces the __OAuth2 authentication support__. A detailed description of this feature can be found in our https://getmesh.io/docs/beta/authentication.html#_oauth2[Authentication Documentation].
____

icon:plus[] Plugins: All plugin endpoints will now automatically be secured via the configured authentication mechanism.

icon:check[] Plugins: The admin client token will no longer expire. The token was previously only valid for one hour.

icon:check[] Plugins: When deployment of a plugin fails during plugin initialization, the plugin can now be redeployed without restarting Gentics Mesh.

icon:check[] Plugins: Fixed a bug which prevented the user client from using the correct token was fixed. The user client will now utilize the correct user token.

[[v0.19.2]]
== 0.19.2 (02.05.2018)

icon:check[] Docker: The base image of the Gentics Mesh docker container has been reverted back to `java:openjdk-8-jre-alpine`. We will switch to Java 10 with the upcoming OrientDB 3.0.0 update.

icon:check[] UI: In some cases the UI did not load fast. We updated the caching mechanism to quickly load the UI after a new Gentics Mesh version has been deployed.

[[v0.19.1]]
== 0.19.1 (30.04.2018)

icon:plus[] REST: The `/api/v1/admin/consistency/repair` endpoint has been added. The endpoint can be used to verify and directly repair found inconsistencies. 
                  The `/api/v1/admin/consistency/check` endpoint response has been updated to also include information about the action which will be performed by `/repair` in order to repair the inconsistency.
                  You can read more about these endpoints in the https://getmesh.io/docs/beta/administration-guide.html#_database_consistency[database consistency] section in our administration documentation.

[[v0.19.0]]
== 0.19.0 (28.04.2018)

icon:bullhorn[] Plugin System

[quote]
____
This version of Gentics Mesh introduces the _Plugin System_. A detailed description of this feature can be found in our https://getmesh.io/docs/beta/plugin-system.html[Plugin System Documentation].
____

icon:plus[] The base image of the Gentics Mesh docker container has been changed to `openjdk:10-slim`.

icon:plus[] Logging: The logging verbosity has been further decreased.

[[v0.18.3]]
== 0.18.3 (25.04.2018)

icon:check[] REST: Add error response when updating a user node reference without specifying the project name.

icon:check[] REST: Fixed the root cause of an inconsistency which caused the deletion of referenced nodes when deleting a node.

[[v0.18.2]]
== 0.18.2 (23.04.2018)

CAUTION: Database revision was updated due to OrientDB update. Thus only an link:https://getmesh.io/docs/beta/clustering.html#_offline_upgrade[offline upgrade] can be performed when using clustered mode.

CAUTION: The generation of the search index document version has been reworked in order to increase index sync performance.
         A triggered index sync will thus re-sync all documents. Triggering the sync action is not required and can be executed at any time.

icon:plus[] Backup/Restore: It is now no longer required to restart the server after a backup has been restored via the `/api/v1/admin/graphdb/restore` endpoint. link:https://github.com/gentics/mesh/issues/387[#387]

icon:plus[] OrientDB: The included OrientDB version has been updated to version 2.2.34

icon:plus[] Consistency: Additional consistency checks have been added.

icon:check[] Consistency: Various consistency issues have been fixed.

icon:check[] REST: Fixed various security related issues.

icon:check[] Core: Image data in binary fields will now only be processed/transformed if the binary is in a readable file format. The readable image file formats are `png`, `jpg`, `bmp` and `gif`.

icon:check[] Core: Added consistency checks for node versions.

icon:check[] Core: Deleting language versions of nodes will no longer create inconsistencies.

icon:check[] Core: Projects containing multiple releases can now be deleted without any error.

[[v0.18.1]]
== 0.18.1 (13.04.2018)

icon:check[] Core: Added consistency check for node containers.

icon:check[] GraphQL: Using filtering with nodes without content does not throw an error anymore.

icon:check[] REST: Added missing `hostname` and `ssl` property handling for release creation requests.

icon:check[] REST: Creating a release with fixed UUID will now invoke the node migration.

icon:check[] Java REST Client: The `eventbus()` method now correctly sends authorization headers.

icon:check[] Java Rest Client: Missing methods to start schema/microschema migrations for a release have been added.

[[v0.18.0]]
== 0.18.0 (06.04.2018)

icon:bullhorn[] GraphQL filtering

[quote]
____
This version of Gentics Mesh introduces _GraphQL filtering_. A detailed description of this feature can be found in our link:https://getmesh.io/docs/beta/graphql.html#_filtering[Documentation].
____

---

CAUTION: Search: The  `/api/v1/search/reindex` endpoint was replaced by `/api/v1/search/sync`.

icon:plus[] Docs: The link:contributing.html[Contribution Guide] has been added.

icon:plus[] The `/api/v1/search/sync` endpoint can now be used to trigger the differential synchronization of search indices. 
            The indices will no longer be dropped and re-populated. Instead only needed actions will be executed to sync the index with the Gentics Mesh data.

icon:plus[] The `/api/v1/search/clear` endpoint has been added. It can be used to re-create all Elasticsearch indices which are managed by Gentics Mesh. 
            Note that this operation does not invoke the index sync.

icon:plus[] Docker: A new volume location for the data directory of the embedded elasticsearch has been added.
                    You can now use the `/elasticsearch/data` folder to mount your elasticsearch data files. link:https://github.com/gentics/mesh/issues/348[#348]

icon:plus[] REST: The `/api/v1/search/status` endpoint has been enhanced. The endpoint will now also return the current elasticsearch sync progress.

icon:plus[] Logging: The logging verbosity has been further decreased.

icon:check[] REST: Fix ETag generation for nodes.
                   Previously taking a node offline did not alter the ETag and this also lead to inconsistent status
                   information being displayed in the Mesh UI link:https://github.com/gentics/mesh/issues/345[#345]

icon:check[] Java Rest Client: Fix webroot requests never returns when containing whitespaces.

icon:check[] GraphQL: Fixed language parameter in nodes query method was ignored in some cases. link:https://github.com/gentics/mesh/issues/365[#365]

icon:check[] REST: The `/api/v1/microschemas` endpoint will now correctly detect name conflicts during microschema creation.

[[v0.17.3]]
== 0.17.3 (15.03.2018)

icon:check[] UI: Restrict nodes to certain schema if allow is set in node list fields.

[[v0.17.2]]
== 0.17.2 (13.03.2018)

icon:plus[] Docker: A new volume location for the `config` directory has been added. 
            You can now use the `/config` folder to mount your configuration files.

icon:plus[] Core: The Vert.x library has been downgraded to 3.5.0 due to a regression which could cause requests to not be handled by the HTTP Server.

[[v0.17.1]]
== 0.17.1 (08.03.2018)

icon:plus[] OrientDB: The included OrientDB version has been updated to version 2.2.33

icon:plus[] Core: The core Vert.x library was updated to version 3.5.1

icon:plus[] Config: It is now possible to configure the elasticsearch start-up timeout via the `search.startupTimeout` field in the `mesh.yml` or via the `MESH_ELASTICSEARCH_STARTUP_TIMEOUT` environment variable.

icon:plus[] Search: The reindex endpoint will now execute the reindex operation asynchronously.

icon:plus[] Search: Two new reindex specific events have been added: `mesh.search.reindex.failed`, `mesh.search.reindex.completed`.

icon:plus[] REST: The `GET /api/v1/search/status` endpoint response has been updated. The `reindexRunning` flag has been added.

icon:check[] Config: Fixed a bug which prevented optional boolean environment variables (e.g. `MESH_HTTP_CORS_ENABLE_ENV`) from being handled correctly.

icon:check[] Core: It is now possible to change the listType of a list field in a schema via the Rest-API.

icon:check[] Core: The server will now shutdown if an error has been detected during start-up.

icon:check[] REST: Fixed an error which led to inconsistent properties being shown in the job endpoint response.

icon:check[] Search: When calling reindex via the `POST /api/v1/search/reindex` endpoint the reindexing stopped after a certain amount of
  time because of a timeout in the database transaction. This has been fixed now.

icon:check[] REST: In some cases parallel file uploads of multiple images could cause the upload process to never finish. This has been fixed now. 

[[v0.17.0]]
== 0.17.0 (22.02.2018)

CAUTION: Search: The raw search endpoints now wraps a multisearch request. The endpoint response will now include the elasticsearch responses array. The query stays the same.

icon:plus[] Demo: The link:https://demo.getmesh.io/demo[demo application] was updated to use Angular 5.

icon:plus[] Core: Gentics Mesh can now be downgraded if the link:https://getmesh.io/docs/beta/administration-guide.html#database-revisions[database revision] matches the needed revision of Gentics Mesh.

icon:plus[] Clustering: Gentics Mesh is now able to form cluster between different server versions. 
			A database revision hash will now be used to determine which versions of Gentics Mesh can form a cluster.
			Only instances with the same database revision hash are allowed to form a cluster.
			The current revision hash info is included in the `/api/v1` endpoint response.

icon:plus[] Various settings can now be overridden via link:https://getmesh.io/docs/beta/administration-guide.html#_environment_variables[environment variables]. This is useful when dealing with docker based deployments.

icon:check[] Elasticsearch: Search requests failed on systems with many schemas. link:https://github.com/gentics/mesh/issues/303[#303]

icon:check[] Elasticsearch: Fixed handling of `search.url` settings which contained a https URL.

icon:check[] Image: The image resizer returned the original image if no `fpx`,`fpy` were present for a focal point image resize request. link:https://github.com/gentics/mesh/issues/272[#272]

icon:check[] Image: The focal point resize returned a slightly skewed image when using the `fpz` zoom factor. link:https://github.com/gentics/mesh/issues/272[#272]

icon:check[] Events: The `mesh.node.deleted` event was not handled correctly. This has been fixed now.

icon:check[] Core: It was possible to upload binaries with empty filenames. This has been fixed now: it is enforced that
				  a binary upload has a filename and content type which are not empty. link:https://github.com/gentics/mesh/issues/299[#299]

icon:check[] Core: If the keystore path was only a file name without a directory a NPE was thrown on start-up. This has been fixed now.

icon:check[] Core: After resetting a job via rest (admin/jobs/::uuid::/error) the job was not processed again.
                  This has been fixed now. link:https://github.com/gentics/mesh/issues/295[#295]

icon:check[] Core: When the migration for multiple nodes failed during a schema migration the error details could become very long.
					This has been fixed now. Error details in the job list will be truncated after a certain amount of characters.

icon:check[] Core: Image transformation calls previously did not copy the image properties of the binary field. 
                   Instead the filename and other properties were not copied to the new binary image field. This has been fixed now.

icon:plus[] REST: It is now possible use custom `HttpClientOptions` upon instantiation of a `MeshRestHttpClient`.

icon:check[] REST: The node response ETag now incorporates the uuids of all node references.

icon:check[] REST: The `/api/v1/auth/logout` endpoint will now correctly delete the `mesh.token` cookie. link:https://github.com/gentics/mesh/issues/282[#282]

[[v0.16.0]]
== 0.16.0 (07.02.2018)

CAUTION: Search: The contents of HTML and HTML list fields will now automatically be stripped of markup prior of indexing.

CAUTION: The `mesh.yml` search section has been updated. The `search.url` property replaces the `search.hosts` property.

[source,json]
----
search:
  url: "http://localhost:9200"
  timeout: 8000
  startEmbedded: false
----

icon:plus[] GraphQL: The underlying graphql-java library was updated to version 7.0.

icon:check[] REST: An error which prevented the `/api/v1` info endpoint from returning version information has been fixed.

icon:plus[] OrientDB: The included OrientDB Studio has been updated to version 2.2.32.

icon:plus[] Config: It is now possible to configure the JVM arguments of the embedded Elasticsearch server via the `search.embeddedArguments` property in the `mesh.yml` file.

icon:plus[] GraphQL: Schema fields can now be queried. Currently supported are `name`, `label`, `required` and `type`.

[[v0.15.0]]
== 0.15.0 (31.01.2018)

CAUTION: The embedded Elasticsearch was removed and replaced by a connector to a dedicated Elasticsearch server. It is highly recommended to verify existing queries due to breaking changes between Elasticsearch version 2.4 and 6.1.
Please also check the Elasticsearch changelog: link:https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-6.1.0.html[Elasticsearch Changelog]

CAUTION: Configuration: The `mesh.yml` format has been updated. Please remove the `search` section or replace it with the following settings.

[source,json]
----
search:
  hosts:
  - hostname: "localhost"
    port: 9200
    protocol: "http"
  startEmbeddedES: true
----

CAUTION: The Elasticsearch update may affect custom mappings within your schemas. You may need to manually update your schemas.

Elasticsearch 6.1 compliant example for the commonly used raw field:

[source,json]
----
{
    "fields": {
        "raw": {
            "type": "keyword",
            "index": true
        }
    }
}
----

CAUTION: The `unfilteredCount` GraphQL paging property has been removed. You can now use the `totalCount` property instead.

CAUTION: Gentics Mesh will automatically extract and start an embedded Elasticsearch server into the `elasticsearch` folder. The old search index (e.g: `data/searchIndex`) can be removed. 

CAUTION: The user which is used to run the process within the docker image has been changed. You may need to update your data volume ownership to uid/gid 1000.

icon:plus[] REST: The UUID of the referenced binary data will now also be listed for binary fields. Fields which share the same binary data will also share the same binary UUID.

icon:plus[] GraphQL: It is now possible to read the focal point information and binary uuid of binary fields.

icon:plus[] Docs: The link:elasticsearch.html[Elasticsearch integration documentation] has been enhanced.

icon:plus[] Search: The overall search performance has been increased.

icon:plus[] Logging: The logging verbosity has been further decreased.

[[v0.14.2]]
== 0.14.2 (30.01.2018)

icon:check[] Elasticsearch: Fixed a bug which caused an internal error when granting multiple permissions to the same element at the same time.

icon:check[] GraphQL: The `linkType` parameter for string and html fields now causes the the link to be rendered in the language of the queried node if no language information is given.

[[v0.14.1]]
== 0.14.1 (19.01.2018)

icon:check[] Core: Fixed a deadlock situation which could occur when handling more than 20 image resize requests in parallel. Image resize operations will now utilize a dedicated thread pool.

icon:check[] Core: Fixed a bug which caused permission inconsistencies when deleting a group from the system.

icon:plus[] REST: Added support to automatically handle the `Expect: 100-Continue` header. We however recommend to only use this header for upload requests.
Using this header will otherwise reduce the response times of your requests. Note that PHP curl will add this header by default.
You can read more about the link:https://support.urbanairship.com/hc/en-us/articles/213492003--Expect-100-Continue-Issues-and-Risks[header here].

[[v0.14.0]]
== 0.14.0 (16.01.2018)

CAUTION: The image manipulation query parameters `cropx`, `cropy`, `croph` and `cropw` have been replaced by the `rect` parameter. The `rect` parameter contains the needed values `rect=x,y,w,h`.

CAUTION: The image manipulation query parameter `width` was renamed to `w`. The parameter `height` was renamed to `h`.

CAUTION: The binary transformation request request was updated. The crop parameters are now nested within the `cropRect` object.

CAUTION: It is now required to specify the crop mode when cropping an image. Possible crop modes are `rect` which will utilize the specified crop area or `fp` which will utilize the focal point information in order to crop the image.

icon:plus[] Image: It is now possible to specify a focal point within the binary field of an image.
                   This focal point can be used to automatically crop the image in a way so that the focused area is kept in the image.
                   The focal point can also be manually specified when requesting an image.
                   This will overrule any previously stored focal point information within the binary field.

icon:plus[] UI: The admin UI has been updated to use the renamed image parameters.

[[v0.13.3]] 
== 0.13.3 (12.01.2018)

icon:check[] Core: Optimized concurrency when handling binary data streams (e.g: downloading, image resizing)

icon:check[] Core: Fixed some bugs which left file handles open and thus clogged the system. This could lead a lock-up of the system in some cases.

[[v0.13.2]]
== 0.13.2 (11.01.2018)

icon:plus[] Java Rest Client: It is now possible to retrieve the client version via `MeshRestClient.getPlainVersion()`.

icon:check[] Core: The consistency checks have been enhanced.

icon:check[] Core: Fixed some bugs which left file handles open and thus clogged the system. This could lead a lock-up of the system in some cases.

[[v0.13.1]]
== 0.13.1 (05.01.2018)

icon:check[] Core: A Vert.x bug has been patched which caused HTTP requests to fail which had the "Connection: close" header set.

icon:check[] REST: A concurrency issue has been addressed which only happens when deleting and creating projects in fast succession.

icon:check[] Core: A potential concurrency issue has been fixed when handling request parameters.

[[v0.13.0]]
== 0.13.0 (02.01.2018)

CAUTION: The Java REST client was updated to use RxJava 2.

icon:plus[] Core: The internal RxJava code has been migrated to version 2.

[[v0.12.0]]
== 0.12.0 (21.12.2017)

CAUTION: The `search.httpEnabled` option within the `mesh.yml` has been removed. The embedded elasticsearch API can no longer be directly accessed via HTTP. The existing endpoint `/api/v1/:projectName/search` is unaffected by this change.

icon:plus[] Core: The core Vert.x library was updated to version 3.5.0

icon:plus[] Core: The internal server routing system has been overhauled.

== 0.11.8 (18.12.2017)

icon:check[] Image: Fixed a bug which left file handles open and thus clogged the system. This could lead a lock-up of the system in some cases.

== 0.11.7 (17.12.2017)

icon:check[] UI: Fixed an issue where the name in the explorer content list in always shown in English. link:https://github.com/gentics/mesh/issues/23[#23]

icon:check[] Storage: Binary field deletion has been made more resilient and will no longer fail if the referenced binary data is not stored within used binary storage. link:https://github.com/gentics/mesh/issues/235[#235]

icon:plus[] REST: The `hostname` and `ssl` properties have been added to the project create request. This information will be directly added to the initial release of the project. The properties can thus be changed by updating the project.

icon:plus[] REST: The link resolver mechanism was enhanced to also consider the `hostname` and `ssl` flag of the release of the node which is linked. 
                  The link resolver will make use of these properties as soon as mesh links point to nodes of foreign projects.
                  You can read more on this topic in the link:https://getmesh.io/docs/beta/features.html#crossdomainlinks[cross domain link section] of our documentation.

== 0.11.6 (15.12.2017)

icon:plus[] Search: The automatic recreation of the search index will now also occur if an empty search index folder was found.

icon:check[] UI: Nodes are now always reloaded when the edit button is clicked in the explorer content list. link:https://github.com/gentics/mesh-ui/issues/16[#16]

icon:check[] UI: Fixed an issue that was causing a click on a node in the explorer list to open it like a container, even if it is not a container.

icon:check[] UI: Dropdowns for required string fields with the allowed attribute now properly require a value to be set in order to save the node.

icon:check[] UI: Fixed a issue where contents of a micronode were not validated before saving a node.

icon:check[] Core: Reduce the memory load of the ChangeNumberStringsToNumber-changelog by reducing the size of a single transactions.

icon:check[] Image: Image handling has been optimized. Previously resizing larger images could temporarily lock up the http server.

== 0.11.5 (14.12.2017)

icon:plus[] UI: Add multi binary upload dialogue. Users can now upload multiple files at once by clicking the button next to the create node button.

icon:plus[] UI: Binary fields can now be used as display fields. The filename is used as the display name for the node. link:https://github.com/gentics/mesh-ui/issues/11[#11]

icon:plus[] UI: It is now possible to specify the URL to the front end of a system. This allows users to quickly go to the page that represents the node in the system.
  See the default `mesh-ui-config.js` or the link:https://getmesh.io/docs/beta/user-interface.html#_configuration[online documentation] for more details. link:https://github.com/gentics/mesh-ui/issues/14[#14]

icon:plus[] Upload: The upload handling code has been refactored in order to process the uploaded data in-parallel.

icon:plus[] Storage: The binary storage mechanism has been overhauled in preparation for Amazon S3 / link:https://minio.io/[Minio] support.
                     The data within the local binary storage folder and all binary fields will automatically be migrated.
                     The created `binaryFilesMigrationBackup` folder must be manually removed once the migration has finished.

icon:plus[] Core: The OrientDB graph database was updated to version 2.2.31

icon:plus[] Core: Binary fields can now be chosen as display fields. The value of the display field is the filename of the binary.

icon:plus[] REST: The display name has been added to the node response. It can be found in the key `displayName`.

icon:plus[] GraphQL: The display name can now be fetched from a node via the `displayName` field.

icon:check[] UI: Nodes in the "Select Node..." dialogue are now sorted by their display name. link:https://github.com/gentics/mesh-ui/issues/15[#15]

icon:check[] UI: The "Select Node..." dialogue now remembers the last position it was opened. link:https://github.com/gentics/mesh-ui/issues/12[#12]

icon:check[] UI: The dropdown for list types in the schema editor now only shows valid list types.

icon:check[] UI: Fixed a bug that causes image preview to disappear after saving a node. link:https://github.com/gentics/mesh-ui/issues/18[#18]

icon:check[] Core: A bug has been fixed which prevented node updates. The issue occurred once a node was updated from which a language variant was previously deleted.

icon:check[] Search: The search index will now automatically be recreated if the search index folder could not be found.

icon:check[] Core: The values of number-fields where stored as strings in the database which caused issues when converting numbers to and from string. 
                   This has been fixed: the values of number-fields will now be stored as numbers.

icon:check[] Schema: The schema deletion process will now also include all schema versions, referenced changes and jobs.

icon:check[] Clustering: A NPE which could occur during initial setup of a clustered instance has been fixed.

== 0.11.4 (07.12.2017)

icon:check[] Core: Fixed various errors which could occur when loading a node for which the editor or creator user has been previously deleted.

== 0.11.3 (30.11.2017)

icon:plus[] Core: Various performance enhancements have been made to increase the concurrency handling and to lower the request times.

icon:plus[] Websocket: It is now possible to register to a larger set of internal events. 
            A full list of all events is documented within the link:https://getmesh.io/docs/beta/features.html#_eventbus_bridge_websocket[eventbus bridge / websocket documentation].

icon:plus[] Config: The eventloop and worker pool size can now be configured within the `mesh.yml` file.

icon:plus[] Logging: The logging verbosity was reduced.

icon:plus[] GraphQL: It is now possible to load a list of all languages of a node via the added `.languages` field.

icon:plus[] GraphQL: The underlying graphql-java library was updated to version 6.0

icon:check[] Core: Fixed a bug which prevented uploading multiple binaries to the same node.

icon:check[] UI: Fixed error message handling for failed save requests.

icon:check[] UI: Fixed the dropdown positioning in IE within the node edit area.

icon:check[] Memory: The memory usage for micronode migrations has been improved.

== 0.11.2 (21.11.2017)

icon:plus[] Core: The OrientDB graph database was updated to version 2.2.30

icon:check[] Core: Fixed a bug which caused unusual high CPU usage. link:https://github.com/gentics/mesh/issues/201[#201]

== 0.11.1 (13.11.2017)

icon:plus[] Elasticsearch: Add support for inline queries.

icon:check[] Elasticsearch: In some cases the connection to Elasticsearch was not directly ready during start up. This caused various issues. A start-up check has been added in order to prevent this.

icon:check[] Schema: A bug within the schema update mechanism which removed the urlField property value has been fixed.

icon:check[] Elasticsearch: A deadlock situation which could occur during schema validation was fixed.

== 0.11.0 (11.11.2017)

CAUTION: GraphQL: The root field `releases` has been removed. The root field `release` now takes no parameters and loads the active release.

CAUTION: Elasticsearch: Search queries will now automatically be wrapped in a boolean query in order to check permissions much more efficiently. 

CAUTION: The schema field property `searchIndex` / `searchIndex.addRaw` has been removed. The property was replaced by a mapping definition which can be added to each field. 
         All schemas will automatically be migrated to the new format. Please keep in mind to also update any existing schema files which you may have stored externally.

```json
{
  "name": "dummySchema",
  "displayField": "name",
  "fields": [
    {
      "name": "name",
      "label": "Name",
      "required": true,
      "type": "string",
      "elasticsearch": {
        "raw": {
          "index": "not_analyzed",
          "type": "string"
        }
      }
    }
  ]
}
```

icon:plus[] Schema: It is now possible to configure index settings and custom search index field mappings within the schema. 

The index settings can be used to define new link:https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-analyzers.html[analyzers] and link:https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-tokenizers.html[tokenizer] or other additional link:https://www.elastic.co/guide/en/elasticsearch/guide/current/_index_settings.html[index settings].
The specified settings will automatically be merged with a default set of settings. 

Once a new analyzer has been defined it can be referenced by custom field mappings which can now be added to each field.
The specified field mapping will be added to the generated fields property of the mapping. You can read more about this topic in the link:https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html[fields mapping documentation] of Elasticsearch.

```json
{
  "name": "dummySchema",
  "displayField": "name",
  "elasticsearch": {
    "settings": {
      "number_of_shards" :   1,
      "number_of_replicas" : 0
    },
    "analysis" : {
      "analyzer" : {
        "suggest" : {
          "tokenizer" : "mesh_default_ngram_tokenizer",
          "char_filter" : [ "html_strip" ],
          "filter" : [ "lowercase" ]
        }
      }
    }
  },
  "fields": [
    {
      "name": "name",
      "label": "Name",
      "required": true,
      "type": "string",
      "elasticsearch": {
        "suggest": {
          "analyzer": "suggest",
          "type": "string"
        }
      }
    }
  ]
}
```

You can use the `POST /api/v1/utilities/validateSchema` endpoint to validate and inspect the effective index configuration.

icon:plus[] REST: The `POST /api/v1/utilities/validateSchema` and `POST /api/v1/utilities/validateMicroschema` endpoints can now be used to validate a schema/microschema JSON without actually storing it.
                     The validation response will also contain the generated Elasticsearch index configuration.

icon:plus[] GraphQL: Nodes can now be loaded in the context of a schema. This will return all nodes which use the schema.

icon:plus[] Search: The `/api/v1/rawSearch/..` and `/api/v1/:projectName/rawSearch/..` endpoints have been added. These can be used to invoke search requests which will return the raw elasticsearch response JSON. 
                       The needed indices will automatically be selected in order to only return the type specific documents. Read permissions on the document will also be automatically checked.

icon:plus[] Search: Error information for failed Elasticsearch queries will now be added to the response.

icon:plus[] Webroot: The schema property `urlFields` can now used to specify fields which contain webroot paths.
                     The webroot endpoint in turn will first try to find a node which specified the requested path.
                     If no path could be found using the urlField values the regular segment path will be used to locate the node.
                     This feature can be used to set custom urls or short urls for your nodes.

icon:check[] Performance: Optimized binary download memory usage.

icon:check[] REST: Fixed a bug which prevented pages with more then 2000 items from being loaded.

== 0.10.4 (10.10.2017)

CAUTION: REST: The `availableLanguages` field now also contains the publish information of the languages of a node.

icon:check[] REST: Fixed a bug in the permission system. Permissions on microschemas will now correctly be updated when applying permission recursively on projects.

icon:check[] REST: ETags will now be updated if the permission on the element changes.

icon:check[] Core: Various bugs within the schema / microschema migration code have been addressed and fixed.

icon:check[] Core: The search index handling has been updated. A differential synchronization will be run to update the new search index and thus the old index data can still be used.

icon:check[] Performance: Removing permissions has been optimized.

icon:plus[] UI: A new action was added to the node action context menu. It is now possible to unpublish nodes.

icon:plus[] UI: The Mesh UI was updated.

icon:plus[] Config: It is now possible to configure the host to which the Gentics Mesh http server should bind to via the `httpServer.host` setting in the `mesh.yml` file. Default is still 0.0.0.0 (all interfaces).

icon:plus[] REST: The `/api/v1/:projectName/releases/:releaseUuid/migrateSchemas` and `/api/v1/:projectName/releases/:releaseUuid/migrateMicroschemas` endpoints have been changed from `GET` to `POST`.

icon:plus[] REST: The `/api/v1/admin/reindex` and `/api/v1/admin/createMappings` endpoints have been changed from `GET` to `POST`.

icon:plus[] CLI: It is now possible to reset the admin password using the `-resetAdminPassword` command line argument.

icon:plus[] GraphQL: The underlying graphql-java library was updated to version 5.0

icon:plus[] Core: The OrientDB graph database was updated to version 2.2.29

== 0.10.3 (18.09.2017)

icon:plus[] Logging: The `logback.xml` default logging configuration file will now be placed in the `config` folder. The file can be used to customize the logging configuration.

icon:plus[] Configuration: It is now possible to set custom properties within the elasticsearch setting.

icon:plus[] Core: The OrientDB graph database was updated to version 2.2.27

icon:plus[] REST: It is now possible to set and read permissions using paths which contain the project name. Example:  `GET /api/v1/roles/:roleUuid/permissions/:projectName/...`

icon:check[] Search: A potential race condition has been fixed. This condition previously caused the elasticsearch to no longer accept any changes.

icon:check[] Performance: The REST API performance has been improved by optimizing the JSON generation process. link:https://github.com/gentics/mesh/issues/141[#141]

== 0.10.2 (14.09.2017)

icon:book[] Documentation: The new link:https://getmesh.io/docs/beta/security.html[security] and link:https://getmesh.io/docs/beta/performance.html[performance] sections have been added to our documentation.

icon:plus[] The *Webroot-Response-Type* header can now be used to differentiate between a webroot binary and node responses. The values of this header can either be *binary* or *node*.

icon:plus[] The `/api/v1/admin/status/migrations` endpoint was removed. 
            The status of a migration job can now be obtained via the `/api/v1/admin/jobs` endpoint. Successfully executed jobs will no longer be removed from the job list.

icon:plus[] The `/api/v1/:projectName/release/:releaseUuid/schemas` and `/api/v1/:projectName/release/:releaseUuid/microschemas` endpoint has been reworked.
            The response format has been updated. The status and uuid of the job which has been invoked when the migration was started will now also be included in this response. 

icon:check[] Java REST Client: A potential threading issue within the Java REST Client has been fixed. Vert.x http clients will no longer be shared across multiple threads.

icon:check[] Memory: Reduce memory footprint of microschema migrations. link:https://github.com/gentics/mesh/issues/135[#135]

icon:check[] Fixed handling "required" and "allow" properties of schema fields when adding fields to schemas.

== 0.10.1 (08.09.2017)

icon:plus[] Clustering: Added link:https://getmesh.io/docs/beta/clustering.html#_node_discovery[documentation] and support for cluster configurations which use a list of static IP adresses instead of multicast discovery.

icon:plus[] Node Migration: The node migration performance has been increased.

icon:plus[] REST: Added new endpoints `/api/v1/admin/jobs` to list and check queued migration jobs. The new endpoints are described in the link:https://getmesh.io/docs/beta/features.html#_executing_migrations[feature documentation].

icon:check[] Search: The `raw` field will no longer be added by default to the search index. Instead it can be added using the new `searchIndex.addRaw` flag within the schema field.
             Please note that the raw field value in the search index will be automatically truncated to a size of 32KB. Otherwise the value can't be added to search index.

icon:check[] Migration: Interrupted migrations will now automatically be started again after the server has been started. Failed migration jobs can be purged or reset via the `/api/v1/admin/jobs` endpoint.

icon:check[] Migration: Migrations will no longer fail if a required field was added. The field will be created and no value will be set. Custom migration scripts can still be used to add a custom default value during migration.

[source,json]
----
{
    "name" : "name",
    "label" : "Name",
    "required" : true,
    "type" : "string",
    "searchIndex": {
        "addRaw": true
    }
}
---- 

icon:check[] Java REST Client: Various missing request parameter implementations have been added to the mesh-rest-client module.

icon:check[] Node Migration: A bug has been fixed which prevented node migrations with more then 5000 elements from completing.

icon:check[] GraphQL: Updated GraphiQL browser to latest version to fix various issues when using aliases.

== 0.10.0 (04.09.2017)


CAUTION: Manual Change: Configuration changes. For already existing `mesh.yml` files, the `nodeName` setting has to be added. Choose any name for the mesh instance.

CAUTION: Manual Change: Configuration changes. The `clusterMode` setting has been deprecated in favour of the new cluster configuration. This setting must be removed from the `mesh.yml` file.

[CAUTION]
=====================================================================
Manual Change: The configuration files `mesh.yml`, `keystore.jceks` must be moved to a subfolder `config` folder.

[source,bash]
----
mkdir config
mv mesh.yml config
mv keystore.jceks config
----
=====================================================================

[CAUTION]
=====================================================================
Manual Change: The graph database folder needs to be moved. Please create the `storage` subfolder and move the existing data into that folder.

[source,bash]
----
mkdir -p data/graphdb/storage
mv data/graphdb/* data/graphdb/storage/
----
=====================================================================

icon:plus[] Clustering: This release introduces the master-master clustering support. You can read more about clustering and the configuration in the link:/docs/beta/clustering.html[clustering documentation].

icon:plus[] Core: The OrientDB graph database was updated to version 2.2.26

icon:plus[] REST: The `/api/v1/admin/consistency/check` endpoint has been added. The endpoint can be used to verify the database integrity.

icon:check[] Core: Fixed missing OrientDB roles and users for some older graph databases. Some graph databases did not create the needed OrientDB user and roles. These roles and users are needed for the OrientDB server and are different from Gentics Mesh users and roles.

icon:check[] REST: Invalid date strings were not correctly handled. An error will now be thrown if a date string can't be parsed.

icon:check[] REST: The delete handling has been updated.
                   It is now possible to specify the `?recursive=true` parameter to recursively delete nodes.
                   By default `?recursive=false` will be used. Deleting a node which contains children will thus cause an error.
                   The behaviour of node language deletion has been updated as well. Deleting the last language of a node will also remove this node. This removal will again fail if no `?recursive=true` query parameter has been added.

== 0.9.28 (28.08.2017)

icon:check[] Core: The permission check system has been updated. The elements which have only `readPublished` permission can now also be read if the user has only `read` permission. The `read` permission automatically also grants `readPublished`.

icon:check[] Java REST Client: The classes `NodeResponse` and `MicronodeField` now correctly implement the interface `FieldContainer`.

icon:check[] REST: The endpoint `/api/v1/{projectName}/nodes/{nodeUuid}/binary/{fieldName}` did not correctly handle the read published nodes permission. This has been fixed now. link:https://github.com/gentics/mesh/issues/111[#111]

== 0.9.27 (23.08.2017)

icon:plus[] GraphQL: It is now possible to retrieve the unfiltered result count. This count is directly loaded from the search provider and may not match up with the exact filtered count.
            The advantage of this value is that it can be retrieved very fast.

icon:plus[] Java REST Client: The client now also supports encrypted connections.

icon:check[] REST: Invalid date were not correctly handled. An error will now be thrown if a date string can't be parsed.

icon:check[] GraphQL: Various errors which occurred when loading a schema of a node via GraphQL have been fixed now.

== 0.9.26 (10.08.2017)

icon:plus[] UI: Added CORS support. Previously CORS was not supported by the UI.

icon:check[] REST API: Added a missing allowed CORS headers which were needed to use the Gentics Mesh UI in a CORS environment.

icon:check[] UI: Fixed translation action. Previously a error prevented translations from being executed.

icon:check[] UI: Fixed image handling for binary fields. Previously only the default language image was displayed in the edit view. This has been fixed.

== 0.9.25 (09.08.2017)

icon:plus[] Demo: The demo dump extraction will now also work if an empty data exists. This is useful when providing a docker mount for the demo data.

icon:plus[] GraphQL: The paging performance has been improved.

icon:plus[] Core: Various missing permission checks have been added.

icon:check[] Core: A bug in the schema changes apply code has been fixed. The bug previously prevented schema changes from being applied.

== 0.9.24 (03.08.2017)

icon:plus[] REST API: Added idempotency checks for various endpoints to prevent execution of superfluous operations. (E.g: Assign role to group, Assign schema to project)

icon:check[] Core: Fixed a bug which prevented micronodes from being transformed. SUP-4751

== 0.9.23 (02.08.2017)

icon:plus[] Rest-Client: It is now possible to configure the base uri for the rest client.

icon:plus[] GraphQL: It is now possible to get the reference of all projects from schemas and microschemas.

icon:check[] UI: Date fields now work with ISO 8601 strings rather than Unix timestamps.

icon:check[] UI: Fixed bugs with lists of microschemas. (SUP-4712)

icon:check[] UI: Fixed mouse clicks not working in lists in FF and (partially) in IE/Edge. (SUP-4717)

icon:check[] Core: The reindex performance has been increased and additional log output will be provided during operations actions.

== 0.9.22 (28.07.2017)

icon:plus[] REST API: It is now possible to create nodes, users, groups, roles, releases and projects using a provided uuid.

icon:check[] Versioning: A publish error which was caused due to a bug in the node language deletion code has been fixed.

== 0.9.21 (26.07.2017)

icon:plus[] Core: The OrientDB graph database was updated to version 2.2.24

icon:check[] Core: Fixed handling of ISO8601 dates which did not contain UTC flag or time offset value. Such dates could previously not be stored. Note that ISO8601 UTC dates will always be returned.

icon:check[] GraphQL: URL handling of the GraphQL browser has been improved. Previously very long queries lead to very long query parameters which could not be handled correctly. The query browser will now use the anchor part of the URL to store the query.

icon:check[] Migration: The error handling within the schema migration code has been improved.

icon:plus[] GraphQL: It is now possible to load the schema version of a node using the ```schema``` field.

icon:check[] Versioning: Older Gentics Mesh instances (>0.8.x) were lacking some draft information. This information has been added now.

== 0.9.20 (21.07.2017)

icon:plus[] License: The license was changed to Apache License 2.0

icon:plus[] Schema Versions: The schema version field type was changed from `number` to `string`. It is now also possible to load schema and microschema versions using the `?version` query parameter.

icon:check[] Search: The error reporting for failing queries has been improved.

icon:check[] Search: The total page count value has been fixed for queries which were using `?perPage=0`.

== 0.9.19 (07.07.2017)

icon:check[] UI: Fixed adding node to node list.

icon:check[] Docs: Various endpoints were not included in the generated RAML. This has been fixed now.

== 0.9.18 (30.06.2017)

icon:plus[] Demo: Fixed demo data uuids.

icon:plus[] Core: The OrientDB graph database was updated to version 2.2.22

icon:plus[] Core: The Ferma OGM library was updated to version 2.2.2

== 0.9.17 (21.06.2017)

icon:check[] UI: A bug which prevented micronodes which contained empty node field from being saved was fixed.

icon:check[] Core: Issues within the error reporting mechanism have been fixed.

icon:plus[] Server: The Mesh UI was added to the mesh-server jar.

icon:plus[] Core: The internal transaction handling has been refactored.

icon:plus[] Core: The Vert.x core dependency was updated to version 3.4.2

icon:plus[] API: The version field of node responses and publish status responses are now strings instead of objects containing the version number.

== 0.9.16 (19.06.2017)

icon:book[] Documentation: Huge documentation update.

== 0.9.15 (19.06.2017)

icon:check[] GraphQL: Fixed loading tags for nodes.

== 0.9.14 (09.06.2017)

icon:check[] WebRoot: Bugs within the permission handling have been fixed. It is now possible to load nodes using only the *read_published* permission. This permission was previously ignored.

icon:check[] GraphQL: An introspection bug which prevented graphiql browser auto completion from working correctly has been fixed. The bug did not occur on systems which already used microschemas. 

== 0.9.13 (08.06.2017)

icon:check[] UI: The UI was updated. An file upload related bug was fixed.

icon:check[] UI: Schema & Microschema description is no longer a required field.

== 0.9.12 (08.06.2017)

icon:check[] GraphQL: Fixed handling of node lists within micronodes.

icon:check[] GraphQL: Fixed Micronode type not found error.

icon:check[] GraphQL: Fixed GraphQL API for system which do not contain any microschemas.

icon:check[] GraphQL: Fixed permission handling and filtering when dealing with node children.

== 0.9.11 (07.06.2017)

icon:plus[] GraphQL: The GraphQL library was updated. Various GraphQL related issues have been fixed.

== 0.9.10 (29.05.2017)

icon:plus[] Schemas: The default content and folder schemas have been updated. The `fileName` and `folderName` fields have been renamed to `slug`. The `name` field was removed from the content schema and a `teaser` field has been added.
These changes are optional and thus not automatically applied to existing installations.

icon:plus[] Demo: The `folderName` and `fileName` fields have been renamed to `slug`. This change only affects new demo installations.


icon:check[] GraphQL: The language fallback handling was overhauled. The default language will no longer be automatically be append to the list of fallback languages. This means that loading nodes will only return nodes in those languages which have been specified by the `lang` argument.

icon:check[] GraphQL: The `path` handling for nodes within node lists has been fixed. Previously it was not possible to retrieve the `path` and various other fields for those nodes.

== 0.9.9 (19.05.2017)

icon:plus[] Core: The OrientDB graph database was updated to version 2.2.20.

icon:plus[] API: The following endpoints were moved:

 * `/api/v1/admin/backup`    `/api/v1/admin/graphdb/backup`
 * `/api/v1/admin/export`    `/api/v1/admin/graphdb/export`
 * `/api/v1/admin/import`    `/api/v1/admin/graphdb/import`
 * `/api/v1/admin/restore`   `/api/v1/admin/graphdb/restore`

icon:plus[] Core: Added `/api/v1/:projectName/releases/:releaseUuid/migrateMicroschemas` endpoint which can be used to resume previously unfinished micronode migrations.

icon:plus[] Performance: The startup performance has been increased when dealing with huge datasets.

icon:plus[] Auth: The anonymous authentication mechanism can now also be disabled by setting the `Anonymous-Authentication: disable` header. This is useful for client applications which don't need or want anonymous authentication. The Gentics Mesh REST client has been enhanced accordingly.

icon:plus[] Core: The read performance of node lists has been improved.

icon:plus[] Core: The write performance of nodes has been improved.

icon:plus[] Demo: The demo data have been updated. The a folderName and fileName field has been added to the demo schemas.

icon:plus[] GraphQL: Added micronode list handling. Previously it was not possible to handle micronode list fields.

icon:check[] Core: Fixed NPE that was thrown when loading releases on older systems.

icon:check[] Core: An upgrade error has been fixed which was caused by an invalid microschema JSON format error.

icon:check[] UI: You will no longer be automatically logged in as anonymous user once your session expires.

icon:check[] Core: The language fallback handling for node breadcrumbs has been fixed. Previously the default language was not automatically added to the handled languages.

== 0.9.8 (08.05.2017)

icon:plus[] UI: Microschemas can now be assigned to projects.

icon:plus[] UI: Descriptions can now be assigned to schemas & microschemas.

icon:plus[] Core: A bug was fixed which prevented the node response `project` property to be populated.

icon:plus[] Core: The redundant `isContainer` field was removed from the node response.

icon:plus[] Core: Various bugs for node migrations have been fixed.

icon:plus[] Core: The allow property for micronode schema fields will now correctly be handled.

icon:plus[] Core: Microschemas will now be assigned to projects during a schema update. This only applies for microschemas which are referenced by the schema (e.g. via a micronode field).

icon:plus[] Core: The OrientDB graph database was updated to version 2.2.19.

== 0.9.7 (28.04.2017)

icon:plus[] GraphQL: The nested `content` and `contents` fields have been removed. The properties of those fields have been merged with the `node` / `nodes` field.

icon:plus[] GraphQL: The field names for paged resultset meta data have been updated to better match up with the REST API fields.

icon:plus[] GraphQL: A language can now be specified when loading node reference fields using the `lang` argument.

icon:plus[] GraphQL: It is now possible to resolve links within loaded fields using the `linkType` field argument.

icon:plus[] Auth: Support for anonymous access has been added to mesh. Requests which do not provide a `mesh.token` will automatically try to use the `anonymous` user. This user is identified by `username` and the thus no anonymous access support is provided if the user can't be located.

icon:plus[] GraphQL: It is now possible to retrieve the path for a content using the `path` field. The `Node.languagePaths` has been removed in favour of this new field.

icon:plus[] Auth: It is now possible to issue API tokens via the `GET /api/v1/users/:userUuid/token` endpoint. API tokens do not expire and work in conjunction with the regular JWT authentication mechanism. These tokens should only be used when SSL is enabled. The `DELETE /api/v1/users/:userUuid/token` endpoint can be used to revoke the issued API token. Only one API token is supported for one user. Generating a new API token will invalidate the previously issued token.

icon:check[] GraphQL: An error was fixed which occurred when loading a node using a bogus uuid.

icon:check[] Auth: An error which caused the keystore loading process to fail was fixed. 

== 0.9.6 (14.04.2017)

icon:plus[] It is now possible to resume previously aborted schema migrations via the `/api/v1/:projectName/releases/:releaseUuid/migrateSchemas` endpoint.

icon:plus[] Auth: The Java keystore file will now automatically be created if none could be found. The keystore password will be taken from the `mesh.yml` file or randomly generated and stored in the config.

icon:check[] Core: Migration errors will no longer cause a migration to be aborted. The migration will continue and log the errors. An incomplete migration can be resumed later on.

icon:check[] Core: Fixed node migration search index handling. Previous migrations did not correctly update the index. A automatic reindex will be invoked during startup.

== 0.9.5 (13.04.2017)

icon:check[] Core: The schema check for duplicate field labels has been removed. The check previously caused schema updates to fail.

== 0.9.4 (13.04.2017)

icon:check[] UI: Fixed project creation.

icon:check[] UI: Fixed error when attempting to translate a node.

icon:check[] UI: Fixed incorrect search query.

icon:check[] UI: Display error when attempting to publish a node with an unpublished ancestor

icon:check[] JWT: The `signatureSecret` property within the Gentics Mesh configuration has been renamed to `keystorePassword`.

icon:plus[] JWT: It is now possible to configure the algorithm which is used to sign the JWT tokens.

icon:plus[] Java: The Java model classes have been updated to provide fluent API's.

icon:plus[] Demo: It is now possible to access elasticsearch head UI directly from mesh via http://localhost:8080/elastichead - The UI will only be provided if the elasticsearch http ports are enabled. Only enable this for development since mesh will not protect the Elasticsearch HTTP server.

icon:plus[] Core: Downgrade and upgrade checks have been added. It is no longer possible to run Gentics Mesh using a dump which contains data which was touched by a newer mesh version. Upgrading a snapshot version of Gentics Mesh to a release version can be performed under advisement.

== 0.9.3 (10.04.2017)

icon:check[] UI: A bug which prevented assigning created schemas to projects was fixed.

icon:check[] A bug which could lead to concurrent request failing was fixed.

icon:check[] Error handling: A much more verbose error will be returned when creating a schema which lacks the type field for certain schema fields.

icon:check[] GraphQL: A bug which lead to incorrect column values for GraphQL errors was fixed.

icon:plus[] The OrientDB dependency was updated to version 2.2.18.

icon:plus[] GraphQL: The container/s field was renamed to content/s to ease usage.

icon:plus[] GraphQL: It is no longer possible to resolve nodes using the provided webroot path. The path argument and the resolving was moved to the `content` field.

== 0.9.2 (04.04.2017)

icon:plus[] The `/api/v1/admin/backup`, `/api/v1/admin/restore`, `/api/v1/admin/import`, `/api/v1/admin/export` endpoints were added to the REST API. These endpoint allow the creation of backup dumps.

icon:plus[] GraphQL: It is now possible to execute elasticsearch queries. within the GraphQL query.

icon:plus[]  GraphQL: It is now possible to resolve a partial web root path using the `child` field of a node.

icon:plus[]  GraphQL: It is now possible to resolve information about the running mesh instance via GraphQL.

icon:check[] Various issues with the linkType argument within the GraphQL API have been fixed.

icon:check[] Fixed NPE that occurred when loading a container for a language which did not exist.

== 0.9.1 (28.03.2017)

icon:check[] The `Access-Control-Allow-Credentials: true` Header will now be returned when CORS support is enabled.

icon:check[] A NullPointerException within the Java Rest Client was fixed.

icon:check[] The AngularJS Demo was updated.

== 0.9.0 (27.03.2017)

icon:plus[] Gentics Mesh now supports GraphQL.

icon:important[] The `expandAll` and `expand` parameters will be removed within an upcoming release of Gentics Mesh. We highly recommend to use the GraphQL endpoint instead if you want to fetch deeply nested data.

icon:plus[] Schema name validation - Schema and microschema names must only contain letter, number or underscore characters.

icon:plus[] Node Tag Endpoint

The endpoint `/api/v1/:projectName/nodes/:nodeUuid/tags` was enhanced. It is now possible to post a list of tag references which will be applied to the node. Tags which are not part of the list will removed from the node. Tags which do not exist will be created. Please note that tag families will not automatically be created.

The `tags` field within the node response was updated accordingly.

== 0.8.3 (24.02.2017)

icon:plus[] Tags are now also indexed in the node document in the field `tagFamilies`, grouped by tag families.

== 0.8.2 (23.02.2017)

icon:check[] The trigram filter configuration was updated so that all characters will be used to tokenize the content.

== 0.8.1 (21.02.2017)

icon:check[] A bug which prevented index creation in certain cases was fixed.

== 0.8.0 (10.02.2017)

icon:plus[] Names, string fields and html field values will now be indexed using the https://www.elastic.co/guide/en/elasticsearch/guide/current/ngrams-compound-words.html[trigram analyzer].

icon:plus[] Binary Endpoint Overhaul

The field API endpoint `/api/v1/:projectName/nodes/:nodeUuid/languages/:language/fields/:field` was removed and replaced by the binary `/api/v1/:projectName/nodes/:nodeUuid/binary` endpoint.
The binary endpoints are now also versioning aware and handle conflict detection. It is thus required to add the `language` and `version` form data parameters to the upload request. 

icon:plus[] Transform Endpoint Overhaul

The endpoint `/api/v1/:projectName/nodes/:nodeUuid/languages/:language/fields/:field/transform` was renamed to `/api/v1/:projectName/nodes/:nodeUuid/binaryTransform`.
The transform endpoint will now return the updated node.  

icon:plus[] The no longer needed schemaReference property was removed from node update requests.

icon:plus[] The rootNodeUuid property within node project response was changed. 

[quote, Example]
____
Old structure:
[source,json]
----
{

  "rootNodeUuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",

}
----

New structure:
[source,json]
----
{

  "rootNode": {
    "uuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
  },

}
----
____

icon:plus[] The parentNodeUuid property within node create requests was changed. 

[quote, Example]
____
Old structure:
[source,json]
----
{

  "parentNodeUuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",

}
----

New structure:
[source,json]
----
{

  "parentNode": {
    "uuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
  },

}
----
____

icon:plus[] JSON Schema information have been added to the RAML API documentation. This information can now be used to generate REST model types for various programming languages.

icon:plus[] The navigation response JSON was restructured. The root element was removed. 

[quote, Example]
____
Old structure:
[source,json]
----
{
  "root" : {
    "uuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
    "node" : {},
    "children" : []
  }
}
----

New structure:
[source,json]
----
{
  "uuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
  "node" : {},
  "children" : []
}
----
____



== 0.7.0 (19.01.2017)

icon:bullhorn[] Content releases support

[quote]
____
This version of Gentics Mesh introduces _Content Releases_. A detailed description of this feature can be found in our https://getmesh.io/docs/beta/index.html[Documentation].
____

icon:bullhorn[] Versioning support

[quote]
____
This version of Gentics Mesh introduces versioning of contents. A detailed description of the versioning feature can be found in our https://getmesh.io/docs/beta/index.html[Documentation].

Important changes summary:

* Node update request must now include the version information
* The query parameter `?version=published` must be used to load published nodes. Otherwise the node will not be found because the default version scope is __draft__.
* Two additional permissions for nodes have been added: __publish__, __readpublished__

Existing databases will automatically be migrated during the first setup.
____

icon:plus[] The missing *availableLanguages* and *defaultLanguage* parameters have been added to the *mesh-ui-config.js* file. Previously no language was configured which removed the option to translate contents.

icon:plus[] Image Property Support - The binary field will now automatically contain properties for image *width*, image *height* and the main *dominant color* in the image.

icon:plus[] API Version endpoint -  It is now possible to load the mesh version information via a `GET` request to `/api/v1/`.

icon:plus[] Project endpoint - The current project information can now be loaded via a `GET` request to `/api/v1/:projectName`.

icon:check[] When the search indices where recreated with the reindex endpoint, the mapping for the raw fields was not added. This has been fixed now.

icon:check[] The search index mapping of fields of type "list" were incorrect and have been fixed now.

icon:check[] Various issues with the schema node migration process have been fixed.

== 0.6.29 (07.03.2017)

icon:plus[] The documentation has been enhanced.

icon:check[] Missing fields could cause error responses. Instead the missing fields will now be set to null instead.

== 0.6.28 (21.10.2016)

icon:check[] Missing fields could cause error responses. Instead the missing fields will now be set to null instead.

== 0.6.27 (07.10.2016)

icon:check[] Various issues with the schema node migration process have been fixed.

== 0.6.26 (05.10.2016)

icon:plus[] The maximum transformation depth limit was raised from 2 to 3.

== 0.6.25 (20.09.2016)

icon:plus[] The used Vert.x version was bumped to 3.3.3.

== 0.6.24 (19.09.2016)

icon:plus[] The Gentics Mesh admin ui has been updated. The UI will no longer send basic auth information for succeeding requests which were invoked after the login action had been invoked. Instead the basic auth login information will only be send directly during login.

icon:check[] A bug within the breadcrumb resolver has been fixed. Previously breadcrumbs did not account for language fallback options and thus returned a 404 path for nodes which used a different language compared to the language of the retrieved node. This has been fixed.

== 0.6.23 (14.09.2016)

icon:check[] The missing availableLanguages and defaultLanguage parameters have been added to the mesh-ui-config.js file. Previously no language was configured which removed the option to translate contents.

== 0.6.22 (24.08.2016)

icon:plus[] It is now possible to publish language variants. Previously it was only possible to publish nodes. This affected all language variants of the node.

== 0.6.21 (17.08.2016)

icon:plus[] The debug output in case of errors has been enhanced.

== 0.6.20 (03.08.2016)

icon:check[] The changelog processing action for existing installations was fixed.

== 0.6.19 (02.08.2016)

icon:check[] Mesh-Admin-UI was updated to version 0.6.13

== 0.6.18 (24.06.2016)

icon:check[] Previously a search request which queried a lot of nodes could result in a StackOverflow exception. The cause for this exception was fixed.

icon:plus[] The gentics/mesh and gentics/mesh-demo images now use the alpine flavour base image and thus the size of the image stack has been reduced.

icon:plus[] The performance of the search endpoints have been improved.

== 0.6.17 (22.06.2016)

icon:check[] The path property within the node response breadcrumb was not set. The property will contain the resolved webroot path for the breadcrumb element. No value will be set if the resolveLinks query parameter was configured or set to OFF. CL-459

== 0.6.16 (21.06.2016)

icon:plus[] Gzip compression support was added. JSON responses are now pretty printed by default.

== 0.6.15 (20.06.2016)

icon:plus[] Mesh-Admin-UI was updated to version 0.6.12

== 0.6.13 (17.06.2016)

icon:plus[] Mesh-Admin-UI was updated to version 0.6.10

== 0.6.12 (02.06.2016)

icon:check[] A bug within the schema migration process was fixed. The label field was previously not correctly handled for newly added fields.

icon:check[] A bug within the schema migration process was fixed. The segmentfield value was reset to null when updating a schema. This has been fixed now.

icon:check[] The "AllChangeProperties" field was removed from the JSON response of schema fields.

== 0.6.11 (31.05.2016)

icon:check[] A bug which prevented node reference deletion was fixed. It is now possible to delete node references using a json null value in update requests.

icon:plus[] OrientDB was updated to version 2.1.18

== 0.6.10 (25.05.2016)

icon:check[] It is now possible to grant and revoke permissions to microschemas using the roles/:uuid/permissions endpoint.

== 0.6.9 (04.05.2016)

icon:plus[] The mesh-ui was updated.

icon:plus[] It is now possible to also include non-container nodes in a navigation response using the includeAll parameter. By default only container nodes will be included in the response.

icon:check[] A minor issue within the webroot path handling of node references was fixed. CL-425

icon:check[] Fixed label and allow field property handling when updating schema fields. CL-357

icon:check[] Various concurrency issues have been addressed.

== 0.6.8 (26.04.2016)

icon:plus[] The mesh-ui was updated.

icon:plus[] OrientDB was updated to version 2.1.16

== 0.6.7 (25.04.2016)

icon:check[] Update checker. A bug that prevented the update checker from working correctly was fixed.

== 0.6.6 (06.04.2016)

icon:bullhorn[] Public open beta release

icon:check[] A bug within the reindex changelog entry was fixed. The bug prevented the node index to be recreated.

icon:check[] The mesh-ui-config.js default apiUrl parameter was changed to /api/v1 in order to allow access from hosts other than localhost.

== 0.6.5 (05.04.2016)

icon:check[] The displayField value was missing within the node search document. The value was added.

icon:check[] The changelog execution information was added to the demo data dump and thus no further changelog execution will happen during mesh demo startup.

icon:check[] An edge case that could cause multiple stack overflow exception was fixed.

icon:plus[] A Cache-Control: no-cache header has been set to mesh responses.

icon:plus[] The mesh-ui was updated.

icon:check[] Various search index related bugs have been fixed.

icon:plus[] The mesh-ui configuration file was renamed to mesh-ui.config.js 

== 0.6.4 (24.03.2016)

icon:plus[] The mesh ui was updated.

== 0.6.3 (22.03.2016)

icon:plus[] Database migration/changelog system.
       A changelog system was added to mesh. The system is used to upgrade mesh data from one mesh version to another.

icon:plus[] The *published* flag can now be referenced within an elasticsearch query.

icon:check[] It was not possible to update the *allow* flag for schema lists (e.g. micronode lists). This has been fixed now.

icon:check[] The schema migration process did not update the node search index correctly. 
       In some cases duplicate nodes would be returned (the old node and the migrated one).
       This has been fixed. Only the latest version of nodes will be returned now.

icon:check[] A NPE was fixed which occurred when updating or creating a node list which included elements which could not be found. (CL-358)

icon:check[] A typo within the search model document for users was fixed.
       The property `emailadress` was renamed to `emailaddress`. 

== 0.6.2 (15.03.2016)

icon:check[] The microschema and schema permission field was always empty for newly created elements.

== 0.6.1 (14.03.2016)

icon:plus[] Added mesh-ui to gentics/mesh docker image

== 0.6.0 (14.03.2016)

icon:plus[] Added image API endpoint
  Images can now be resized and cropped using the image endpoint.

icon:plus[] Added schema versioning

icon:plus[] Added schema migration process
  It is now possible to update schemas. Custom migration 
  handlers can be defined in order to modify the node data.

icon:plus[] Added Micronodes/Microschemas
  A new field type has been added which allows creation of micronodes.

icon:plus[] Webroot API
  The webroot REST endpoint was added which allows easy retrieval of nodes by its web path.

icon:plus[] JWT Authentication support has been added
  It is now possible to select JWT in order to authenticate the user.
  
icon:plus[] Navigation Endpoint
  The navigation REST endpoint was added which allows retrieval of navigation tree data which can be used to render navigations.

icon:plus[] Added docker support
  It is now possible to start mesh using the gentics/mesh or gentics/mesh-demo docker image.

icon:plus[] Vert.x update
  The Vert.x dependency was updated to version 3.2.1

icon:check[] Fixed paging issue for nested tags

== 0.5.0 (17.11.2015)

icon:important[] Closed beta release
