:icons: font

= Gentics Mesh Changelog

== 0.10.5 (TBD)

CAUTION: GraphQL: The root field releases has been removed. The root field release now takes no parameters and loads the active release.
icon:plus[] GraphQL: Nodes can now be loaded in the context of a schema. This will return all nodes which use the schema.

CAUTION: Elasticsearch: Search queries will now automatically be wrapped in a boolean query in order to check permissions much more efficiently. 

icon:check[] Performance: Optimized binary download memory usage.

icon:check[] REST: Fixed a bug which prevented pages with more then 2000 items from being loaded.

== 0.10.4 (10.10.2017)

CAUTION: REST: The `availableLanguages` field now also contains the publish information of the languages of a node.

icon:check[] REST: Fixed a bug in the permission system. Permissions on microschemas will now correctly be updated when applying permission recursively on projects.

icon:check[] REST: ETags will now be updated if the permission on the element changes.

icon:check[] Core: Various bugs within the schema / microschema migration code have been addressed and fixed.

icon:check[] Core: The search index handling has been updated. A differential synchronization will be run to update the new search index and thus the old index data can still be used.

icon:check[] Performance: Removing permissions has been optimized.

icon:plus[] UI: A new action was added to the node action context menu. It is now possible to unpublish nodes.

icon:plus[] UI: The Mesh UI was updated.

icon:plus[] Config: It is now possible to configure the host to which the Gentics Mesh http server should bind to via the `httpServer.host` setting in the `mesh.yml` file. Default is still 0.0.0.0 (all interfaces).

icon:plus[] REST: The `/api/v1/:projectName/releases/:releaseUuid/migrateSchemas` and `/api/v1/:projectName/releases/:releaseUuid/migrateMicroschemas` endpoints have been changed from `GET` to `POST`.

icon:plus[] REST: The `/api/v1/admin/reindex` and `/api/v1/admin/createMappings` endpoints have been changed from `GET` to `POST`.

icon:plus[] CLI: It is now possible to reset the admin password using the `-resetAdminPassword` command line argument.

icon:plus[] GraphQL: The underlying graphql-java library was updated to version 5.0

icon:plus[] Core: The OrientDB graph database version was updated to version 2.2.29

== 0.10.3 (18.09.2017)

icon:plus[] Logging: The `logback.xml` default logging configuration file will now be placed in the `config` folder. The file can be used to customize the logging configuration.

icon:plus[] Configuration: It is now possible to set custom properties within the elasticsearch setting.

icon:plus[] Core: The OrientDB graph database version was updated to version 2.2.27

icon:plus[] REST: It is now possible to set and read permissions using paths which contain the project name. Example:  `GET /api/v1/roles/:roleUuid/permissions/:projectName/...`

icon:check[] Search: A potential race condition has been fixed. This condition previously caused the elasticsearch to no longer accept any changes.

icon:check[] Performance: The REST API performance has been improved by optimizing the JSON generation process. link:https://github.com/gentics/mesh/issues/141[#141]

== 0.10.2 (14.09.2017)

icon:book[] Documentation: The new link:https://getmesh.io/docs/beta/security.html[security] and link:https://getmesh.io/docs/beta/performance.html[performance] sections have been added to our documentation.

icon:plus[] The *Webroot-Response-Type* header can now be used to differentiate between a webroot binary and node responses. The values of this header can either be *binary* or *node*.

icon:plus[] The `/api/v1/admin/status/migrations` endpoint was removed. 
            The status of a migration job can now be obtained via the `/api/v1/admin/jobs` endpoint. Successfully executed jobs will no longer be removed from the job list.

icon:plus[] The `/api/v1/:projectName/release/:releaseUuid/schemas` and `/api/v1/:projectName/release/:releaseUuid/microschemas` endpoint has been reworked.
            The response format has been updated. The status and uuid of the job which has been invoked when the migration was started will now also be included in this response. 

icon:check[] Java REST Client: A potential threading issue within the Java REST Client has been fixed. Vert.x http clients will no longer be shared across multiple threads.

icon:check[] Memory: Reduce memory footprint of microschema migrations. link:https://github.com/gentics/mesh/issues/135[#135]

icon:check[] Fixed handling "required" and "allow" properties of schema fields when adding fields to schemas.

== 0.10.1 (08.09.2017)

icon:plus[] Clustering: Added link:https://getmesh.io/docs/beta/clustering.html#_node_discovery[documentation] and support for cluster configurations which use a list of static IPs instead of multicast discovery.

icon:plus[] Node Migration: The node migration performance has been increased.

icon:plus[] REST: Added new endpoints `/api/v1/admin/jobs` to list and check queued migration jobs. The new endpoints are described in the link:https://getmesh.io/docs/beta/features.html#_executing_migrations[feature documentation].

icon:check[] Search: The `raw` field will no longer be added by default to the search index. Instead it can be added using the new `searchIndex.addRaw` flag within the schema field.
             Please note that the raw field value in the search index will be automatically truncated to a size of 32KB. Otherwise the value can't be added to search index.

icon:check[] Migration: Interrupted migrations will now automatically be started again after the server has been started. Failed migration jobs can be purged or reset via the `/api/v1/admin/jobs` endpoint.

icon:check[] Migration: Migrations will no longer fail if a required field was added. The field will be created and no value will be set. Custom migration scripts can still be used to add a custom default value during migration.

[source,json]
----
{
    "name" : "name",
    "label" : "Name",
    "required" : true,
    "type" : "string",
    "searchIndex": {
        "addRaw": true
    }
}
---- 

icon:check[] Java REST Client: Various missing request parameter implementations have been added to the mesh-rest-client module.

icon:check[] Node Migration: A bug has been fixed which prevented node migrations with more then 5000 elements from completing.

icon:check[] GraphQL: Updated graphiql browser to latest version to fix various issues when using aliases.

== 0.10.0 (04.09.2017)


CAUTION: Manual Change: Configuration changes. For already existing `mesh.yml` files, the `nodeName` setting has to be added. Choose any name for the mesh instance.

CAUTION: Manual Change: Configuration changes. The `clusterMode` setting has been deprecated in favour of the new cluster configuration. This setting must be removed from the `mesh.yml` file.

[CAUTION]
=====================================================================
Manual Change: The configuration files `mesh.yml`, `keystore.jceks` must be moved to a subfolder `config` folder.

[source,bash]
----
mkdir config
mv mesh.yml config
mv keystore.jceks config
----
=====================================================================

[CAUTION]
=====================================================================
Manual Change: The graph database folder needs to be moved. Please create the `storage` subfolder and move the existing data into that folder.

[source,bash]
----
mkdir -p data/graphdb/storage
mv data/graphdb/* data/graphdb/storage/
----
=====================================================================

icon:plus[] Clustering: This release introduces the master-master clustering support. You can read more about clustering and the configuration in the link:/docs/beta/clustering.html[clustering documentation].

icon:plus[] Core: The OrientDB graph database version was updated to version 2.2.26

icon:plus[] REST: The `/api/v1/admin/consistency/check` endpoint has been added. The endpoint can be used to verify the database integrity.

icon:check[] Core: Fixed missing OrientDB roles and users for some older graph databases. Some graph databases did not create the needed OrientDB user and roles. These roles and users are needed for the OrientDB server and are different from Gentics Mesh users and roles.

icon:check[] REST: Invalid date strings were not correctly handled. An error will now be thrown if a date string can't be parsed.

icon:check[] REST: The delete handling has been updated.
                   It is now possible to specify the `?recursive=true` parameter to recursively delete nodes.
                   By default `?recursive=false` will be used. Deleting a node which contains children will thus cause an error.
                   The behaviour of node language deletion has been updated as well. Deleting the last language of a node will also remove this node. This removal will again fail if no `?recursive=true` query parameter has been added.

== 0.9.28 (28.08.2017)

icon:check[] Core: The permission check system has been updated. The elements which have only `readPublished` permission can now also be read if the user has only `read` permission. The `read` permission automatically also grants `readPublished`.

icon:check[] Java REST Client: The classes `NodeResponse` and `MicronodeField` now correctly implement the interface `FieldContainer`.

icon:check[] REST: The endpoint `/api/v1/{projectName}/nodes/{nodeUuid}/binary/{fieldName}` did not correctly handle the read published nodes permission. This has been fixed now. link:https://github.com/gentics/mesh/issues/111[#111]

== 0.9.27 (23.08.2017)

icon:plus[] GraphQL: It is now possible to retrieve the unfiltered result count. This count is directly loaded from the search provider and may not match up with the exact filtered count.
            The advantage of this value is that it can be retrieved very fast.

icon:plus[] Java REST Client: The client now also supports encrypted connections.

icon:check[] REST: Invalid date were not correctly handled. An error will now be thrown if a date string can't be parsed.

icon:check[] GraphQL: Various errors which occurred when loading a schema of a node via GraphQL have been fixed now.

== 0.9.26 (10.08.2017)

icon:plus[] UI: Added CORS support. Previously CORS was not supported by the UI.

icon:check[] REST API: Added a missing allowed CORS headers which were needed to use the Gentics Mesh UI in a CORS environment.

icon:check[] UI: Fixed translation action. Previously a error prevented translations from being executed.

icon:check[] UI: Fixed image handling for binary fields. Previously only the default language image was displayed in the edit view. This has been fixed.

== 0.9.25 (09.08.2017)

icon:plus[] Demo: The demo dump extraction will now also work if an empty data exists. This is useful when providing a docker mount for the demo data.

icon:plus[] GraphQL: The paging performance has been improved.

icon:plus[] Core: Various missing permission checks have been added.

icon:check[] Core: A bug in the schema changes apply code has been fixed. The bug previously prevented schema changes from being applied.

== 0.9.24 (03.08.2017)

icon:plus[] REST API: Added idempotency checks for various endpoints to prevent execution of superfluous operations. (E.g: Assign role to group, Assign schema to project)

icon:check[] Core: Fixed a bug which prevented micronodes from being transformed. SUP-4751

== 0.9.23 (02.08.2017)

icon:plus[] Rest-Client: It is now possible to configure the base uri for the rest client.

icon:plus[] GraphQL: It is now possible to get the reference of all projects from schemas and microschemas.

icon:check[] UI: Date fields now work with ISO 8601 strings rather than unix timestamps.

icon:check[] UI: Fixed bugs with lists of microschemas. (SUP-4712)

icon:check[] UI: Fixed mouse clicks not working in lists in FF and (partially) in IE/Edge. (SUP-4717)

icon:check[] Core: The reindex performance has been increased and additional log output will be provided during operations actions.

== 0.9.22 (28.07.2017)

icon:plus[] REST API: It is now possible to create nodes, users, groups, roles, releases and projects using a provided uuid.

icon:check[] Versioning: A publish error which was caused due to a bug in the node language deletion code has been fixed.

== 0.9.21 (26.07.2017)

icon:plus[] Core: The OrientDB graph database version was updated to version 2.2.24

icon:check[] Core: Fixed handling of ISO8601 dates which did not contain UTC flag or time offset value. Such dates could previously not be stored. Note that ISO8601 UTC dates will always be returned.

icon:check[] GraphQL: URL handling of the GraphQL browser has been improved. Previously very long queries lead to very long query parameters which could not be handled correctly. The query browser will now use the anchor part of the URL to store the query.

icon:check[] Migration: The error handling within the schema migration code has been improved.

icon:plus[] GraphQL: It is now possible to load the schema version of a node using the ```schema``` field.

icon:check[] Versioning: Older Gentics Mesh instances (>0.8.x) were lacking some draft information. This information has been added now.

== 0.9.20 (21.07.2017)

icon:plus[] License: The license was changed to Apache License 2.0

icon:plus[] Schema Versions: The schema version field type was changed from `number` to `string`. It is now also possible to load schema and microschema versions using the `?version` query parameter.

icon:check[] Search: The error reporting for failing queries has been improved.

icon:check[] Search: The total page count value has been fixed for queries which were using `?perPage=0`.

== 0.9.19 (07.07.2017)

icon:check[] UI: Fixed adding node to node list.

icon:check[] Docs: Various endpoints were not included in the generated RAML. This has been fixed now.

== 0.9.18 (30.06.2017)

icon:plus[] Demo: Fixed demo data uuids.

icon:plus[] Core: The OrientDB graph database version was updated to version 2.2.22

icon:plus[] Core: The Ferma OGM library was updated to version 2.2.2

== 0.9.17 (21.06.2017)

icon:check[] UI: A bug which prevented micronodes which contained empty node field from being saved was fixed.

icon:check[] Core: Issues within the error reporting mechanism have been fixed.

icon:plus[] Server: The Mesh UI was added to the mesh-server jar.

icon:plus[] Core: The internal transaction handling has been refactored.

icon:plus[] Core: The Vert.x core dependency was updated to version 3.4.2

icon:plus[] API: The version field of node responses and publish status responses are now strings instead of objects containing the version number.

== 0.9.16 (19.06.2017)

icon:book[] Documentation: Huge documentation update.

== 0.9.15 (19.06.2017)

icon:check[] GraphQL: Fixed loading tags for nodes.

== 0.9.14 (09.06.2017)

icon:check[] WebRoot: Bugs within the permission handling have been fixed. It is now possible to load nodes using only the *read_published* permission. This permission was previously ignored.

icon:check[] GraphQL: An introspection bug which prevented graphiql browser autocompletion from working correctly has been fixed. The bug did not occur on systems which already used microschemas. 

== 0.9.13 (08.06.2017)

icon:check[] UI: The UI was updated. An file upload related bug was fixed.

icon:check[] UI: Schema & Microschema description is no longer a required field.

== 0.9.12 (08.06.2017)

icon:check[] GraphQL: Fixed handling of node lists within micronodes.

icon:check[] GraphQL: Fixed Micronode type not found error.

icon:check[] GraphQL: Fixed GraphQL API for system which do not contain any microschemas.

icon:check[] GraphQL: Fixed permission handling and filtering when dealing with node children.

== 0.9.11 (07.06.2017)

icon:plus[] GraphQL: The GraphQL library was updated. Various GraphQL related issues have been fixed.

== 0.9.10 (29.05.2017)

icon:plus[] Schemas: The default content and folder schemas have been updated. The `fileName` and `folderName` fields have been renamed to `slug`. The `name` field was removed from the content schema and a `teaser` field has been added.
These changes are optional and thus not automatically applied to existing installations.

icon:plus[] Demo: The `folderName` and `fileName` fields have been renamed to `slug`. This change only affects new demo installations.


icon:check[] GraphQL: The language fallback handling was overhauled. The default language will no longer be automatically be append to the list of fallback languages. This means that loading nodes will only return nodes in those languages which have been specified by the `lang` argument.

icon:check[] GraphQL: The `path` handling for nodes within node lists has been fixed. Previously it was not possible to retrieve the `path` and various other fields for those nodes.

== 0.9.9 (19.05.2017)

icon:plus[] Core: The OrientDB graph database version was updated to version 2.2.20.

icon:plus[] API: The following endpoints were moved:

 * `/api/v1/admin/backup`  ⟶  `/api/v1/admin/graphdb/backup`
 * `/api/v1/admin/export`  ⟶  `/api/v1/admin/graphdb/export`
 * `/api/v1/admin/import`  ⟶  `/api/v1/admin/graphdb/import`
 * `/api/v1/admin/restore` ⟶  `/api/v1/admin/graphdb/restore`

icon:plus[] Core: Added `/api/v1/:projectName/releases/:releaseUuid/migrateMicroschemas` endpoint which can be used to resume previously unfinished micronode migrations.

icon:plus[] Performance: The startup performance has been increased when dealing with huge datasets.

icon:plus[] Auth: The anonymous authentication mechanism can now also be disabled by setting the `Anonymous-Authentication: disable` header. This is useful for client applications which don't need or want anonymous authentication. The Gentics Mesh REST client has been enhanced accordingly.

icon:plus[] Core: The read performance of node lists has been improved.

icon:plus[] Core: The write performance of nodes has been improved.

icon:plus[] Demo: The demo data have been updated. The a folderName and fileName field has been added to the demo schemas.

icon:plus[] GraphQL: Added micronode list handling. Previously it was not possible to handle micronode list fields.

icon:check[] Core: Fixed NPE that was thrown when loading releases on older systems.

icon:check[] Core: An upgrade error has been fixed which was caused by an invalid microschema JSON format error.

icon:check[] UI: You will no longer be automatically logged in as anonymous user once your session expires.

icon:check[] Core: The language fallback handling for node breadcrumbs has been fixed. Previously the default language was not automatically added to the handled languages.

== 0.9.8 (08.05.2017)

icon:plus[] UI: Microschemas can now be assigned to projects.

icon:plus[] UI: Descriptions can now be assigned to schemas & microschemas.

icon:plus[] Core: A bug was fixed which prevented the node response `project` property to be populated.

icon:plus[] Core: The redundant `isContainer` field was removed from the node response.

icon:plus[] Core: Various bugs for node migrations have been fixed.

icon:plus[] Core: The allow property for micronode schema fields will now correctly be handled.

icon:plus[] Core: Microschemas will now be assigned to projects during a schema update. This only applies for microschemas which are referenced by the schema (e.g.: via a micronode field).

icon:plus[] Core: The OrientDB graph database version was updated to version 2.2.19.

== 0.9.7 (28.04.2017)

icon:plus[] GraphQL: The nested `content` and `contents` fields have been removed. The properties of those fields have been merged with the `node` / `nodes` field.

icon:plus[] GraphQL: The field names for paged resultset meta data have been updated to better match up with the REST API fields.

icon:plus[] GraphQL: A language can now be specified when loading node reference fields using the `lang` argument.

icon:plus[] GraphQL: It is now possible to resolve links within loaded fields using the `linkType` field argument.

icon:plus[] Auth: Support for anonymous access has been added to mesh. Requests which do not provide a `mesh.token` will automatically try to use the `anonymous` user. This user is identified by `username` and the thus no anonymous access support is provided if the user can't be located.

icon:plus[] GraphQL: It is now possible to retrieve the path for a content using the `path` field. The `Node.languagePaths` has been removed in favour of this new field.

icon:plus[] Auth: It is now possible to issue API tokens via the `GET /api/v1/users/:userUuid/token` endpoint. API tokens do not expire and work in conjunction with the regular JWT authentication mechanism. These tokens should only be used when SSL is enabled. The `DELETE /api/v1/users/:userUuid/token` endpoint can be used to revoke the issued API token. Only one API token is supported for one user. Generating a new API token will invalidate the previously issued token.

icon:check[] GraphQL: An error was fixed which occurred when loading a node using a bogus uuid.

icon:check[] Auth: An error which caused the keystore loading process to fail was fixed. 

== 0.9.6 (14.04.2017)

icon:plus[] It is now possible to resume previously aborted schema migrations via the `/api/v1/:projectName/releases/:releaseUuid/migrateSchemas` endpoint.

icon:plus[] Auth: The Java keystore file will now automatically be created if none could be found. The keystore password will be taken from the `mesh.yml` file or randomly generated and stored in the config.

icon:check[] Core: Migration errors will no longer cause a migration to be aborted. The migration will continue and log the errors. An incomplete migration can be resumed later on.

icon:check[] Core: Fixed node migration search index handling. Previous migrations did not correctly update the index. A automatic reindex will be invoked during startup.

== 0.9.5 (13.04.2017)

icon:check[] Core: The schema check for duplicate field labels has been removed. The check previously caused schema updates to fail.

== 0.9.4 (13.04.2017)

icon:check[] UI: Fixed project creation.

icon:check[] UI: Fixed error when attempting to translate a node.

icon:check[] UI: Fixed incorrect search query.

icon:check[] UI: Display error when attempting to publish a node with an unpublished ancestor

icon:check[] JWT: The `signatureSecret` property within the Gentics Mesh configuration has been renamed to `keystorePassword`.

icon:plus[] JWT: It is now possible to configure the algorithm which is used to sign the JWT tokens.

icon:plus[] Java: The Java model classes have been updated to provide fluent API's.

icon:plus[] Demo: It is now possible to access elasticsearch head UI directly from mesh via http://localhost:8080/elastichead - The UI will only be provided if the elasticsearch http ports are enabled. Only enable this for development since mesh will not protect the Elasticsearch HTTP server.

icon:plus[] Core: Downgrade and upgrade checks have been added. It is no longer possible to run Gentics Mesh using a dump which contains data which was touched by a newer mesh version. Upgrading a snapshot version of Gentics Mesh to a release version can be performed under advisement.

== 0.9.3 (10.04.2017)

icon:check[] UI: A bug which prevented assigning created schemas to projects was fixed.

icon:check[] A bug which could lead to concurrent request failing was fixed.

icon:check[] Error handling: A much more verbose error will be returned when creating a schema which lacks the type field for certain schema fields.

icon:check[] GraphQL: A bug which lead to incorrect column values for graphql errors was fixed.

icon:plus[] The OrientDB dependency was updated to version 2.2.18.

icon:plus[] GraphQL: The container/s field was renamed to content/s to ease usage.

icon:plus[] GraphQL: It is no longer possible to resolve nodes using the provided webroot path. The path argument and the resolving was moved to the `content` field.

== 0.9.2 (04.04.2017)

icon:plus[] The `/api/v1/admin/backup`, `/api/v1/admin/restore`, `/api/v1/admin/import`, `/api/v1/admin/export` endpoints were added to the REST API. These endpoint allow the creation of backup dumps.

icon:plus[] GraphQL: It is now possible to execute elasticsearch queries. within the graphql query.

icon:plus[]  GraphQL: It is now possible to resolve a partial web root path using the `child` field of a node.

icon:plus[]  GraphQL: It is now possible to resolve information about the running mesh instance via graphql.

icon:check[] Various issues with the linkType argument within the GraphQL API have been fixed.

icon:check[] Fixed NPE that occurred when loading a container for a language which did not exist.

== 0.9.1 (28.03.2017)

icon:check[] The `Access-Control-Allow-Credentials: true` Header will now be returned when CORS support is enabled.

icon:check[] A NullPointerException within the Java Rest Client was fixed.

icon:check[] The AngularJS Demo was updated.

== 0.9.0 (27.03.2017)

icon:plus[] Gentics Mesh now supports GraphQL.

icon:important[] The `expandAll` and `expand` parameters will be removed within an upcoming release of Gentics Mesh. We highly recommend to use the GraphQL endpoint instead if you want to fetch deeply nested data.

icon:plus[] Schema name validation - Schema and microschema names must only contain letter, number or underscore characters.

icon:plus[] Node Tag Endpoint

The endpoint `/api/v1/:projectName/nodes/:nodeUuid/tags` was enhanced. It is now possible to post a list of tag references which will be applied to the node. Tags which are not part of the list will removed from the node. Tags which do not exist will be created. Please note that tag families will not automatically be created.

The `tags` field within the node response was updated accordingly.

== 0.8.3 (24.02.2017)

icon:plus[] Tags are now also indexed in the node document in the field `tagFamilies`, grouped by tag families.

== 0.8.2 (23.02.2017)

icon:check[] The trigram filter configuration was updated so that all characters will be used to tokenize the content.

== 0.8.1 (21.02.2017)

icon:check[] A bug which prevented index creation in certain cases was fixed.

== 0.8.0 (10.02.2017)

icon:plus[] Names, string fields and html field values will now be indexed using the https://www.elastic.co/guide/en/elasticsearch/guide/current/ngrams-compound-words.html[trigram analyzer].

icon:plus[] Binary Endpoint Overhaul

The field API endpoint `/api/v1/:projectName/nodes/:nodeUuid/languages/:language/fields/:field` was removed and replaced by the binary `/api/v1/:projectName/nodes/:nodeUuid/binary` endpoint.
The binary endpoints are now also versioning aware and handle conflict detection. It is thus required to add the `language` and `version` form data parameters to the upload request. 

icon:plus[] Transform Endpoint Overhaul

The endpoint `/api/v1/:projectName/nodes/:nodeUuid/languages/:language/fields/:field/transform` was renamed to `/api/v1/:projectName/nodes/:nodeUuid/binaryTransform`.
The transform endpoint will now return the updated node.  

icon:plus[] The no longer needed schemaReference property was removed from node update requests.

icon:plus[] The rootNodeUuid property within node project response was changed. 

[quote, Example]
____
Old structure:
[source,json]
----
{
…
  "rootNodeUuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
…
}
----

New structure:
[source,json]
----
{
…
  "rootNode": {
    "uuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
  },
…
}
----
____

icon:plus[] The parentNodeUuid property within node create requests was changed. 

[quote, Example]
____
Old structure:
[source,json]
----
{
…
  "parentNodeUuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
…
}
----

New structure:
[source,json]
----
{
…
  "parentNode": {
    "uuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
  },
…
}
----
____

icon:plus[] JSON Schema information have been added to the RAML API documentation. This information can now be used to generate REST model types for various programming languages.

icon:plus[] The navigation response JSON was restructured. The root element was removed. 

[quote, Example]
____
Old structure:
[source,json]
----
{
  "root" : {
    "uuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
    "node" : {…},
    "children" : […]
  }
}
----

New structure:
[source,json]
----
{
  "uuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
  "node" : {…},
  "children" : […]
}
----
____



== 0.7.0 (19.01.2017)

icon:bullhorn[] Content releases support

[quote]
____
This version of Gentics Mesh introduces _Content Releases_. A detailed description of this feature can be found in our https://getmesh.io/docs/beta/index.html[Documentation].
____

icon:bullhorn[] Versioning support

[quote]
____
This version of Gentics Mesh introduces versioning of contents. A detailed description of the versioning feature can be found in our https://getmesh.io/docs/beta/index.html[Documentation].

Important changes summary:

* Node update request must now include the version information
* The query parameter `?version=published` must be used to load published nodes. Otherwise the node will not be found because the default version scope is __draft__.
* Two additional permissions for nodes have been added: __publish__, __readpublished__

Existing databases will automatically be migrated during the first setup.
____

icon:plus[] The missing *availableLanguages* and *defaultLanguage* parameters have been added to the *mesh-ui-config.js* file. Previously no language was configured which removed the option to translate contents.

icon:plus[] Image Property Support - The binary field will not automatically contain properties for image *width*, image *height* and the main *dominant color* in the image.

icon:plus[] API Version endpoint -  It is now possible to load the mesh version information via a `GET` request to `/api/v1/`.

icon:plus[] Project endpoint - The current project information can now be loaded via a `GET` request to `/api/v1/:projectName`.

icon:check[] When the search indices where recreated with the reindex endpoint, the mapping for the raw fields was not added. This has been fixed now.

icon:check[] The search index mapping of fields of type "list" were incorrect and have been fixed now.

icon:check[] Various issues with the schema node migration process have been fixed.

== 0.6.29 (07.03.2017)

icon:plus[] The documentation has been enhanced.

icon:check[] Missing fields could cause error responses. Instead the missing fields will now be set to null instead.

== 0.6.28 (21.10.2016)

icon:check[] Missing fields could cause error responses. Instead the missing fields will now be set to null instead.

== 0.6.27 (07.10.2016)

icon:check[] Various issues with the schema node migration process have been fixed.

== 0.6.26 (05.10.2016)

icon:plus[] The maximum transformation depth limit was raised from 2 to 3.

== 0.6.25 (20.09.2016)

icon:plus[] The used Vert.x version was bumped to 3.3.3.

== 0.6.24 (19.09.2016)

icon:plus[] The Gentics Mesh admin ui has been updated. The UI will no longer send basic auth information for succeeding requests which were invoked after the login action had been invoked. Instead the basic auth login information will only be send directly during login.

icon:check[] A bug within the breadcrumb resolver has been fixed. Previouly breadcrumbs did not account for language fallback options and thus returned a 404 path for nodes which used a different language compared to the language of the retrieved node. This has been fixed.

== 0.6.23 (14.09.2016)

icon:check[] The missing availableLanguages and defaultLanguage parameters have been added to the mesh-ui-config.js file. Previously no language was configured which removed the option to translate contents.

== 0.6.22 (24.08.2016)

icon:plus[] It is now possible to publish language variants. Previously it was only possible to publish nodes. This affected all language variants of the node.

== 0.6.21 (17.08.2016)

icon:plus[] The debug output in case of errors has been enhanced.

== 0.6.20 (03.08.2016)

icon:check[] The changelog processing action for existing installations was fixed.

== 0.6.19 (02.08.2016)

icon:check[] Mesh-Admin-UI was updated to version 0.6.13

== 0.6.18 (24.06.2016)

icon:check[] Previously a search request which queried a lot of nodes could result in a StackOverflow exception. The cause for this exception was fixed.

icon:plus[] The gentics/mesh and gentics/mesh-demo images now use the alpine flavour base image and thus the size of the image stack has been reduced.

icon:plus[] The performance of the search endpoints have been improved.

== 0.6.17 (22.06.2016)

icon:check[] The path property within the node response breadcrumb was not set. The property will contain the resolved webroot path for the breadcrumb element. No value will be set if the resolveLinks query parameter was configured or set to OFF. CL-459

== 0.6.16 (21.06.2016)

icon:plus[] Gzip compression support was added. JSON responses are now pretty printed by default.

== 0.6.15 (20.06.2016)

icon:plus[] Mesh-Admin-UI was updated to version 0.6.12

== 0.6.13 (17.06.2016)

icon:plus[] Mesh-Admin-UI was updated to version 0.6.10

== 0.6.12 (02.06.2016)

icon:check[] A bug within the schema migration process was fixed. The label field was previously not correctly handled for newly added fields.

icon:check[] A bug within the schema migration process was fixed. The segmentfield value was reset to null when updating a schema. This has been fixed now.

icon:check[] The "AllChangeProperties" field was removed from the JSON response of schema fields.

== 0.6.11 (31.05.2016)

icon:check[] A bug which prevented node reference deletion was fixed. It is now possible to delete node references using a json null value in update requests.

icon:plus[] OrientDB was updated to version 2.1.18

== 0.6.10 (25.05.2016)

icon:check[] It is now possible to grant and revoke permissions to microschemas using the roles/:uuid/permissions endpoint.

== 0.6.9 (04.05.2016)

icon:plus[] The mesh-ui was updated.

icon:plus[] It is now possible to also include non-container nodes in a navigation response using the includeAll parameter. By default only container nodes will be included in the response.

icon:check[] A minor issue within the webroot path handling of node references was fixed. CL-425

icon:check[] Fixed label and allow field property handling when updating schema fields. CL-357

icon:check[] Various concurrency issues have been addressed.

== 0.6.8 (26.04.2016)

icon:plus[] The mesh-ui was updated.

icon:plus[] OrientDB was updated to version 2.1.16

== 0.6.7 (25.04.2016)

icon:check[] Update checker. A bug that prevented the update checker from working correctly was fixed.

== 0.6.6 (06.04.2016)

icon:bullhorn[] Public open beta release

icon:check[] A bug within the reindex changelog entry was fixed. The bug prevented the node index to be recreated.

icon:check[] The mesh-ui-config.js default apiUrl parameter was changed to /api/v1 in order to allow access from hosts other than localhost.

== 0.6.5 (05.04.2016)

icon:check[] The displayField value was missing within the node search document. The value was added.

icon:check[] The changelog execution information was added to the demo data dump and thus no further changelog execution will happen during mesh demo startup.

icon:check[] An edge case that could cause multiple stack overflow exception was fixed.

icon:plus[] A Cache-Control: no-cache header has been set to mesh responses.

icon:plus[] The mesh-ui was updated.

icon:check[] Various search index related bugs have been fixed.

icon:plus[] The mesh-ui configuration file was renamed to mesh-ui.config.js 

== 0.6.4 (24.03.2016)

icon:plus[] The mesh ui was updated.

== 0.6.3 (22.03.2016)

icon:plus[] Database migration/changelog system.
       A changelog system was added to mesh. The system is used to upgrade mesh data from one mesh version to another.

icon:plus[] The *published* flag can now be referenced within an elasticsearch query.

icon:check[] It was not possible to update the *allow* flag for schema lists (e.g.: micronode lists). This has been fixed now.

icon:check[] The schema migration process did not update the node search index correctly. 
       In some cases duplicate nodes would be returned (the old node and the migrated one).
       This has been fixed. Only the latest version of nodes will be returned now.

icon:check[] A NPE was fixed which occurred when updating or creating a node list which included elements which could not be found. (CL-358)

icon:check[] A typo within the search model document for users was fixed.
       The property emailadress was renamed to emailaddress. 

== 0.6.2 (15.03.2016)

icon:check[] The microschema and schema permission field was always empty for newly created elements.

== 0.6.1 (14.03.2016)

icon:plus[] Added mesh-ui to gentics/mesh docker image

== 0.6.0 (14.03.2016)

icon:plus[] Added image API endpoint
  Images can now be resized and cropped using the image endpoint.

icon:plus[] Added schema versioning

icon:plus[] Added schema migration process
  It is now possible to update schemas. Custom migration 
  handlers can be defined in order to modify the node data.

icon:plus[] Added Micronodes/Microschemas
  A new field type has been added which allows creation of micronodes.

icon:plus[] Webroot API
  The webroot REST endpoint was added which allows easy retrieval of nodes by its web path.

icon:plus[] JWT Authentication support has been added
  It is now possible to select JWT in order to authenticate the user.
  
icon:plus[] Navigation Endpoint
  The navigation REST endpoint was added which allows retrieval of navigation tree data which can be used to render navigations.

icon:plus[] Added docker support
  It is now possible to start mesh using the gentics/mesh or gentics/mesh-demo docker image.

icon:plus[] Vertx update
  The Vertx dependency was updated to version 3.2.1

icon:check[] Fixed paging issue for nested tags

== 0.5.0 (17.11.2015)

icon:important[] Closed beta release
