:icons: font

= Gentics Mesh Changelog

== 0.8.0

icon:plus[] Schema name validation - Schema and microschema names must only contain letter, number or underscore characters.

icon:plus[] Node Tag Endpoint

The endpoint `/api/v1/:projectName/nodes/:nodeUuid/tags` was enhanced. It is now possible to post a list of tag references which will be applied to the node. Tags which are not part of the list will removed from the node. Tags which do not exist will be created. Please note that tag families will not automatically be created.

The `tags` field within the node response was updated accordingly.

icon:plus[] Names, string fields and html field values will now be indexed using the https://www.elastic.co/guide/en/elasticsearch/guide/current/ngrams-compound-words.html[trigram analyzer].

icon:plus[] Tags are now also indexed in the node document in the field `tagFamilies`, grouped by tag families.

icon:plus[] Binary Endpoint Overhaul

The field API endpoint `/api/v1/:projectName/nodes/:nodeUuid/languages/:language/fields/:field` was removed and replaced by the binary `/api/v1/:projectName/nodes/:nodeUuid/binary` endpoint.
The binary endpoints are now also versioning aware and handle conflict detection. It is thus required to add the `language` and `version` form data parameters to the upload request. 

icon:plus[] Transform Endpoint Overhaul

The endpoint `/api/v1/:projectName/nodes/:nodeUuid/languages/:language/fields/:field/transform` was renamed to `/api/v1/:projectName/nodes/:nodeUuid/binaryTransform`.
The transform endpoint will now return the updated node.  

icon:plus[] The no longer needed schemaReference property was removed from node update requests.

icon:plus[] The rootNodeUuid property within node project response was changed. 

[quote, Example]
____
Old structure:
[source,json]
----
{
…
  "rootNodeUuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
…
}
----

New structure:
[source,json]
----
{
…
  "rootNode": {
    "uuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
  },
…
}
----
____

icon:plus[] The parentNodeUuid property within node create requests was changed. 

[quote, Example]
____
Old structure:
[source,json]
----
{
…
  "parentNodeUuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
…
}
----

New structure:
[source,json]
----
{
…
  "parentNode": {
    "uuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
  },
…
}
----
____

icon:plus[] JSON Schema information have been added to the RAML API documentation. This information can now be used to generate REST model types for various programming languages.

icon:plus[] The navigation response JSON was restructured. The root element was removed. 

[quote, Example]
____
Old structure:
[source,json]
----
{
  "root" : {
    "uuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
    "node" : {…},
    "children" : […]
  }
}
----

New structure:
[source,json]
----
{
  "uuid" : "cd5ac8943a4448ee9ac8943a44a8ee25",
  "node" : {…},
  "children" : […]
}
----
____

== 0.7.0 (SNAPSHOT)

icon:bullhorn[] Content releases support

[quote]
____
This version of Gentics Mesh introduces _Content Releases_. A detailed description of this feature can be found in our http://getmesh.io/docs/beta/index.html[Documentation].
____

icon:bullhorn[] Versioning support

[quote]
____
This version of Gentics Mesh introduces versioning of contents. A detailed description of the versioning feature can be found in our http://getmesh.io/docs/beta/index.html[Documentation].

Important changes summary:

* Node update request must now include the version information
* The query parameter `?version=published` must be used to load published nodes. Otherwise the node will not be found because the default version scope is __draft__.
* Two additional permissions for nodes have been added: __publish__, __readpublished__

Existing databases will automatically be migrated during the first setup.
____

icon:plus[] The missing *availableLanguages* and *defaultLanguage* parameters have been added to the *mesh-ui-config.js* file. Previously no language was configured which removed the option to translate contents.

icon:plus[] Image Property Support - The binary field will not automatically contain properties for image *width*, image *height* and the main *dominant color* in the image.

icon:plus[] API Version endpoint -  It is now possible to load the mesh version information via a `GET` request to `/api/v1/`.

icon:plus[] Project endpoint - The current project information can now be loaded via a `GET` request to `/api/v1/:projectName`.

icon:check[] When the search indices where recreated with the reindex endpoint, the mapping for the raw fields was not added. This has been fixed now.

icon:check[] The search index mapping of fields of type "list" were incorrect and have been fixed now.

icon:check[] Various issues with the schema node migration process have been fixed.

== 0.6.26 (05.10.2016)

icon:plus[] The maximum transformation depth limit was raised from 2 to 3.

== 0.6.25 (20.09.2016)

icon:plus[] The used Vert.x version was bumped to 3.3.3.

== 0.6.24 (19.09.2016)

icon:plus[] The Gentics Mesh admin ui has been updated. The UI will no longer send basic auth information for succeeding requests which were invoked after the login action had been invoked. Instead the basic auth login information will only be send directly during login.

icon:check[] A bug within the breadcrumb resolver has been fixed. Previouly breadcrumbs did not account for language fallback options and thus returned a 404 path for nodes which used a different language compared to the language of the retrieved node. This has been fixed.

== 0.6.23 (14.09.2016)

icon:check[] The missing availableLanguages and defaultLanguage parameters have been added to the mesh-ui-config.js file. Previously no language was configured which removed the option to translate contents.

== 0.6.22 (24.08.2016)

icon:plus[] It is now possible to publish language variants. Previously it was only possible to publish nodes. This affected all language variants of the node.

== 0.6.21 (17.08.2016)

icon:plus[] The debug output in case of errors has been enhanced.

== 0.6.20 (03.08.2016)

icon:check[] The changelog processing action for existing installations was fixed.

== 0.6.19 (02.08.2016)

icon:check[] Mesh-Admin-UI was updated to version 0.6.13

== 0.6.18 (24.06.2016)

icon:check[] Previously a search request which queried a lot of nodes could result in a StackOverflow exception. The cause for this exception was fixed.

icon:plus[] The gentics/mesh and gentics/mesh-demo images now use the alpine flavour base image and thus the size of the image stack has been reduced.

icon:plus[] The performance of the search endpoints have been improved.

== 0.6.17 (22.06.2016)

icon:check[] The path property within the node response breadcrumb was not set. The property will contain the resolved webroot path for the breadcrumb element. No value will be set if the resolveLinks query parameter was configured or set to OFF. CL-459

== 0.6.16 (21.06.2016)

icon:plus[] Gzip compression support was added. JSON responses are now pretty printed by default.

== 0.6.15 (20.06.2016)

icon:plus[] Mesh-Admin-UI was updated to version 0.6.12

== 0.6.13 (17.06.2016)

icon:plus[] Mesh-Admin-UI was updated to version 0.6.10

== 0.6.12 (02.06.2016)

icon:check[] A bug within the schema migration process was fixed. The label field was previously not correctly handled for newly added fields.

icon:check[] A bug within the schema migration process was fixed. The segmentfield value was reset to null when updating a schema. This has been fixed now.

icon:check[] The "AllChangeProperties" field was removed from the JSON response of schema fields.

== 0.6.11 (31.05.2016)

icon:check[] A bug which prevented node reference deletion was fixed. It is now possible to delete node references using a json null value in update requests.

icon:plus[] OrientDB was updated to version 2.1.18

== 0.6.10 (25.05.2016)

icon:check[] It is now possible to grant and revoke permissions to microschemas using the roles/:uuid/permissions endpoint.

== 0.6.9 (04.05.2016)

icon:plus[] The mesh-ui was updated.

icon:plus[] It is now possible to also include non-container nodes in a navigation response using the includeAll parameter. By default only container nodes will be included in the response.

icon:check[] A minor issue within the webroot path handling of node references was fixed. CL-425

icon:check[] Fix label and allow field property handling when updating schema fields. CL-357

icon:check[] Various concurrency issues have been addressed.

== 0.6.8 (26.04.2016)

icon:plus[] The mesh-ui was updated.

icon:plus[] OrientDB was updated to version 2.1.16

== 0.6.7 (25.04.2016)

icon:check[] Update checker. A bug that prevented the update checker from working correctly was fixed.

== 0.6.6 (06.04.2016)

* Public open beta release
icon:check[] A bug within the reindex changelog entry was fixed. The bug prevented the node index to be recreated.

icon:check[] The mesh-ui-config.js default apiUrl parameter was changed to /api/v1 in order to allow access from hosts other than localhost.

== 0.6.5 (05.04.2016)

icon:check[] The displayField value was missing within the node search document. The value was added.

icon:check[] The changelog execution information was added to the demo data dump and thus no further changelog execution will happen during mesh demo startup.

icon:check[] An edge case that could cause multiple stack overflow exception was fixed.

icon:plus[] A Cache-Control: no-cache header has been set to mesh responses.

icon:plus[] The mesh-ui was updated.

icon:check[] Various search index related bugs have been fixed.

icon:plus[] The mesh-ui configuration file was renamed to mesh-ui.config.js 

== 0.6.4 (24.03.2016)

icon:plus[] The mesh ui was updated.

== 0.6.3 (22.03.2016)

icon:plus[] Database migration/changelog system.
       A changelog system was added to mesh. The system is used to upgrade mesh data from one mesh version to another.

icon:plus[] The *published* flag can now be referenced within an elasticsearch query.

icon:check[] It was not possible to update the *allow* flag for schema lists (e.g.: micronode lists). This has been fixed now.

icon:check[] The schema migration process did not update the node search index correctly. 
       In some cases duplicate nodes would be returned (the old node and the migrated one).
       This has been fixed. Only the latest version of nodes will be returned now.
icon:check[] It was not possible to update the *allow* flag for schema lists (e.g.: micronode lists). This has been fixed now.

icon:check[] A NPE was fixed which occurred when updating or creating a node list which included elements which could not be found. (CL-358)

icon:check[] A typo within the search model document for users was fixed.
       The property emailadress was renamed to emailaddress. 

== 0.6.2 (15.03.2016)

icon:check[] The microschema and schema permission field was always empty for newly created elements.

== 0.6.1 (14.03.2016)

icon:plus[] Add mesh-ui to gentics/mesh docker image

== 0.6.0 (14.03.2016)

icon:plus[] Added image API endpoint
  Images can now be resized and cropped using the image endpoint.

icon:plus[] Added schema versioning

icon:plus[] Added schema migration process
  It is now possible to update schemas. Custom migration 
  handlers can be defined in order to modify the node data.

icon:plus[] Added Micronodes/Microschemas
  A new field type has been added which allows creation of micronodes.

icon:plus[] Webroot API
  The webroot REST endpoint was added which allows easy retrieval of nodes by its web path.

icon:plus[] JWT Authentication support has been added
  It is now possible to select JWT in order to authenticate the user.
  
icon:plus[] Navigation Endpoint
  The navigation REST endpoint was added which allows retrieval of navigation tree data which can be used to render navigations.

icon:plus[] Added docker support
  It is now possible to start mesh using the gentics/mesh or gentics/mesh-demo docker image.

icon:plus[] Vertx update
  The Vertx dependency was updated to version 3.2.1

icon:check[] Fixed paging issue for nested tags

== 0.5.0 (17.11.2015)

icon:important[] Closed beta release
