package com.gentics.mesh.search.index.node;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.util.Optional;

import org.junit.Test;

import com.gentics.mesh.core.rest.schema.FieldSchema;
import com.gentics.mesh.core.rest.schema.impl.BinaryFieldSchemaImpl;
import com.gentics.mesh.core.rest.schema.impl.S3BinaryFieldSchemaImpl;
import com.gentics.mesh.etc.config.MeshOptions;
import com.gentics.mesh.etc.config.NativeQueryFiltering;
import com.gentics.mesh.etc.config.search.MappingMode;
import com.gentics.mesh.search.impl.Elasticsearch7ComplianceImpl;

import io.vertx.core.json.JsonObject;

/**
 * Unit tests for the field mappings, generated by {@link NodeContainerMappingProviderImpl}.
 */
public class NodeContainerMappingProviderImplTest {

	@Test
	public void testBinaryFieldCustomMappingInStrictMode() {
		JsonObject customMapping = customMapping();
		FieldSchema field = new BinaryFieldSchemaImpl().setName("binary").setElasticsearch(customMapping);

		Optional<JsonObject> mapping = provider(MappingMode.STRICT).getFieldMapping(field, null, null);

		assertTrue("The mapping of the binary field must be present", mapping.isPresent());
		assertEquals("The mapping of the binary field must be the custom mapping", customMapping, mapping.get());
	}

	@Test
	public void testS3BinaryFieldCustomMappingInStrictMode() {
		JsonObject customMapping = customMapping();
		FieldSchema field = new S3BinaryFieldSchemaImpl().setName("s3binary").setElasticsearch(customMapping);

		Optional<JsonObject> mapping = provider(MappingMode.STRICT).getFieldMapping(field, null, null);

		assertTrue("The mapping of the s3binary field must be present", mapping.isPresent());
		assertEquals("The mapping of the s3binary field must be the custom mapping", customMapping, mapping.get());
	}

	@Test
	public void testBinaryFieldMappingInDynamicMode() {
		FieldSchema field = new BinaryFieldSchemaImpl().setName("binary");

		JsonObject mapping = provider(MappingMode.DYNAMIC).getFieldMapping(field, null, null).get();

		assertEquals("object", mapping.getString("type"));
		JsonObject props = mapping.getJsonObject("properties");
		assertEquals("keyword", props.getJsonObject("sha512sum").getString("type"));
		assertEquals("keyword", props.getJsonObject("filename").getString("type"));
	}

	@Test
	public void testS3BinaryFieldMappingInDynamicMode() {
		FieldSchema field = new S3BinaryFieldSchemaImpl().setName("s3binary");

		JsonObject mapping = provider(MappingMode.DYNAMIC).getFieldMapping(field, null, null).get();

		assertEquals("object", mapping.getString("type"));
		JsonObject props = mapping.getJsonObject("properties");
		assertEquals("keyword", props.getJsonObject("s3ObjectKey").getString("type"));
		assertEquals("keyword", props.getJsonObject("filename").getString("type"));
	}

	private static JsonObject customMapping() {
		return new JsonObject()
			.put("type", "object")
			.put("properties", new JsonObject()
				.put("filename", new JsonObject().put("type", "keyword").put("index", true))
				.put("mimeType", new JsonObject().put("type", "keyword").put("index", true)));
	}

	private static NodeContainerMappingProviderImpl provider(MappingMode mode) {
		MeshOptions options = new MeshOptions() {
			@Override
			public NativeQueryFiltering getNativeQueryFiltering() {
				return NativeQueryFiltering.NEVER;
			}

			@Override
			public MeshOptions setNativeQueryFiltering(NativeQueryFiltering nativeQueryFiltering) {
				return this;
			}

			@Override
			public boolean hasDatabaseLevelCache() {
				return false;
			}
		};
		options.getSearchOptions().setMappingMode(mode);
		return new NodeContainerMappingProviderImpl(options, new Elasticsearch7ComplianceImpl());
	}
}
