#!/bin/bash

styles="default default_themed amelia cerulean cosmo cyborg darkly flatly journal lumen united readable simplex slate spacelab superhero yeti"

for i in $styles
do
   echo creating css/bootstrap_$i.css
   lessc --global-var="bsw-root='https://raw.githubusercontent.com/thomaspark/bootswatch/gh-pages'" src/less/styles/$i/styles.less css/bootstrap_$i.css
   cleancss -o css/bootstrap_$i.min.css css/bootstrap_$i.css
done
