FROM    java:openjdk-8-jre-alpine

USER root

RUN mkdir /mesh
RUN adduser -D -u 1000 -h /mesh mesh
RUN chown mesh: /mesh
RUN echo "mesh:mesh" | chpasswd

USER mesh
WORKDIR /mesh
ADD bin /mesh/bin
ADD run.sh /mesh/run.sh

USER root
RUN chmod +x /mesh/run.sh
RUN mkdir /data && mkdir /config && ln -s /data /mesh/data && chown mesh: /data &&  chown mesh: /config && ln -s /config /mesh/config

USER mesh
VOLUME /data
VOLUME /config

EXPOSE 8080
CMD  ["/mesh/run.sh"]
