= Changelog

=== 0.5.0 - 17.11.2015

* Closed beta release

=== 0.6.0 - 14.03.2016

* Enhancement: Added image API endpoint
  Images can now be resized and cropped using the image endpoint.

* Enhancement: Added schema versioning

* Enhancement: Added schema migration process
  It is now possible to update schemas. Custom migration 
  handlers can be defined in order to modify the node data.

* Enhancement: Added Micronodes/Microschemas
  A new field type has been added which allows creation of micronodes.

* Enhancement: Webroot API
  The webroot REST endpoint was added which allows easy retrieval of nodes by its web path.

* Enhancement: JWT Authentication support has been added
  It is now possible to select JWT in order to authenticate the user.
  
* Enhancement: Navigation Endpoint
  The navigation REST endpoint was added which allows retrieval of navigation tree data which can be used to render navigations.

* Enhancement: Added docker support
  It is now possible to start mesh using the gentics/mesh or gentics/mesh-demo docker image.

* Fix: Fixed paging issue for nested tags

* Enhancement: Vertx update
  The Vertx dependency was updated to version 3.2.1


=== 0.6.1 - 14.03.2016

* Enhancement: Add mesh-ui to gentics/mesh docker image

=== 0.6.2 - 15.03.2016

* Fix: The microschema and schema permission field was always empty for newly created elements.

=== 0.6.3 - 22.03.2016

* Enhancement: Database migration/changelog system.
       A changelog system was added to mesh. The system is used to upgrade mesh data from one mesh version to another.
* Enhancement: The *published* flag can now be referenced within an elasticsearch query.
* Fix: It was not possible to update the *allow* flag for schema lists (e.g.: micronode lists). This has been fixed now.
* Fix: The schema migration process did not update the node search index correctly. 
       In some cases duplicate nodes would be returned (the old node and the migrated one).
       This has been fixed. Only the latest version of nodes will be returned now.
* Fix: It was not possible to update the *allow* flag for schema lists (e.g.: micronode lists). This has been fixed now.
* Fix: A NPE was fixed which occurred when updating or creating a node list which included elements which could not be found. (CL-358)
* Fix: A typo within the search model document for users was fixed.
       The property emailadress was renamed to emailaddress. 

=== 0.6.4 - 24.03.2016

* Enhancement: The mesh ui was updated.

=== 0.6.5 - 05.04.2016

* Fix: The displayField value was missing within the node search document. The value was added.
* Fix: The changelog execution information was added to the demo data dump and thus no further changelog execution will happen during mesh demo startup.
* Fix: An edge case that could cause multiple stack overflow exception was fixed.
* Enhancement: A Cache-Control: no-cache header has been set to mesh responses.
* Enhancement: The mesh-ui was updated.
* Fix: Various search index related bugs have been fixed.
* Enhancement: The mesh-ui configuration file was renamed to mesh-ui.config.js 

=== 0.6.6 - 06.04.2016

* Public open beta release
* Fix: A bug within the reindex changelog entry was fixed. The bug prevented the node index to be recreated.
* Fix: The mesh-ui-config.js default apiUrl parameter was changed to /api/v1 in order to allow access from hosts other than localhost.

=== 0.6.7 - 25.04.2016

* Fix: Update checker. A bug that prevented the update checker from working correctly was fixed.

=== 0.6.8 - 26.04.2016

* Enhancement: The mesh-ui was updated.
* Enhancement: OrientDB was updated to version 2.1.16

=== 0.6.9 - 28.04.2016

* Enhancement: It is now possible to also include non-container nodes in a navigation response using the includeAll parameter. By default only container nodes will be included in the response.
* Fix: A minor issue within the webroot path handling of node references was fixed. CL-425
* Fix: Fix label and allow field property handling when updating schema fields. CL-357

=== 0.6.10 - 29.04.2016

* Fix: Various concurrency issues have been addressed.

=== Upcoming changes

* Versioning for nodes
  A future mesh version will also support versioning of nodes.

* Java REST Client
  A Rest client which supports RXJava will be added.

* Clustering support
