= Getting Started Guide

== Quickstart

----
Oracle Java Runtime 1.8.0_40 or newer is required to run Gentics Mesh.
----

. Download Gentics Mesh from http://getmesh.io/Download into an *empty* folder
. Start the JAR-file by executing ```java -jar mesh-demo-X.X.X.jar```
. Point your browser to http://localhost:8080/mesh-ui/ to reach the Mesh Admin UI

== Startup

Run Gentics Mesh by executing ```java -jar mesh-demo-X.X.X.jar```. All neccessary configuration files and directories will
be created and an AngularJS demo project is deployed automatically.

Once the demo setup is completed you will be able to access the following urls

* Mesh API ```http://localhost:8080/api/v1/```
* Mesh UI on ```http://localhost:8080/mesh-ui/```
* Demo App on ```http://localhost:8080/demo/```

*Demo Credentials*

* Admin: ```admin/admin```
* Editor: ```editor/editor```
* Webclient: ```webclient/webclient```

== Demo

Once the Mesh setup is complete, a demo application will be automatically deployed to the install location under the ```demo``` folder. This demo app is accessible at ```http://localhost:8080/demo/```, and is intended as a simple example of how Mesh can be used.

The app is composed of static files and can therefore be edited in place. The two JavaScript files which make up the app contain in-line documentation to help you get started.

