= Documentation

++++
<style>
ul.doc-toc, ul.doc-toc ul {
    list-style: none;
    line-height:150%;
    padding-left: 0px;
}

ul.doc-toc ul ul {
    padding-left: 15px;
}

ul.doc-toc h2 {
    font-size: 27px;
}
</style>

<div class="container docs-content">
    <div class="row">
        <div class="col-sm-12">
            <div id="preamble">
                <div class="sectionbody">
                    <div class="paragraph">
                        <p>
                        Gentics Mesh is a headless or API-first CMS shipped with a single JAR file. <br/>
                        This is the right place for <a href="getting-started.html">getting started</a> using Gentics Mesh. 
                            <ul>
                                <li>The <a href="getting-started.html#_tldr">TL;DR</a> section will briefly explain everything you should know and what makes Gentics Mesh special.</li>
                                <li>Our <a href="getting-started.html#_quickstart">Quickstart</a> guide will let you play with Gentics Mesh in seconds - No installation is required. Just download a single JAR file!</li>
                                <li>You will find an overview of the <a href="building-blocks.html">core concepts</a>, a complete list of all <a href="features.html">features</a> and <a href="references.html">references</a> for available APIs, such as REST and GraphQL. </li>
                                <li>To get you started, we have collected a set of samples for different <a href="platforms.html">platforms</a>, i.e. JavaScript, Java, GO, and PHP .
                                <li>The <a href="administration-guide.html">administration guide</a>, will provide information on how to configure and run Gentics Mesh in your environment.</li>
                            </ul>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="col-md-4">
                <ul class="doc-toc">
                    <li class="section">
                        <h2><a href="getting-started.html">Getting Started</a></h2>
                        <ul>
                            <li>
                                <a href="getting-started.html#_quickstart">Quickstart</a>
                            </li>
                            <li>
                                <a href="getting-started.html#_tldr">TL;DR</a>
                            </li>
                        </ul>
                    </li>
                    <li class="section">
                        <h2><a href="building-blocks.html">Building Blocks</a></h2>
                        <ul>
                            <li>
                                <a href="building-blocks.html#_project">Project</a>
                            </li>
                            <li>
                                <a href="building-blocks.html#_node">Node</a>
                            </li>
                            <li>
                                <a href="building-blocks.html#_schema">Schema</a>
                            </li>
                            <li>
                                <a href="building-blocks.html#_micronode">Micronode &amp; Microschema</a>
                            </li>
                            <li>
                                <a href="building-blocks.html#_tag">Tag</a>
                            </li>
                            <li>
                                <a href="building-blocks.html#_tag_family">Tag Family</a>
                            </li>
                            <li>
                                <a href="building-blocks.html#_user">User</a>
                            </li>
                            <li>
                                <a href="building-blocks.html#_group">Group</a>
                            </li>
                            <li>
                                <a href="building-blocks.html#_role">Role</a>
                            </li>
                        </ul>
                    </li>
                    <li class="section">
                        <h2><a href="administration-guide.html">Administration Guide</a></h2>
                        <ul>
                            <li>
                                <a href="administration-guide.html#_software_stack">Software Stack</a>
                            </li>
                            <li>
                                <a href="administration-guide.html#_run_with_jar_file">Run with JAR File</a>
                            </li>
                            <li>
                                <a href="administration-guide.html#_run_with_docker">Run with Docker</a>
                            </li>
                            <li>
                                <a href="administration-guide.html#_installation_directory">Installation Directory</a>
                            </li>                            
                            <li>
                                <a href="administration-guide.html#_system_requirements">System Requirements</a>
                            </li>
                            <li>
                                <a href="administration-guide.html#_configuration_settings">Configuration & Settings</a>
                            </li>
                            <li>
                                <a href="administration-guide.html#_backup_recovery">Backup &amp; Recovery</a>
                            </li>                            
                            <li>
                                <a href="changelog.html">Changelog</a>
                            </li>
                            <li>
                                <a href="administration-guide.html#_license">License</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="doc-toc">
                    <li class="section">
                        <h2><a href="features.html">Features</a></h2>
                        <ul>
                            <li>
                                <a href="features.html#contenttree">Content Tree</a>
                            </li>
                            <li>
                                <a href="features.html#prettyurls">Pretty URLs</a>
                            </li>
                            <li>
                                <a href="features.html#navigation">Navigation Menus</a>
                            </li>
                            <li>
                                <a href="features.html#_breadcrumbs">Breadcrumbs</a>
                            </li>
                            <li>
                                <a href="features.html#webroot">Fetching Content with WebRoot Paths</a>
                            </li>
                            <li>
                                <a href="features.html#_link_resolving">Link Resolving</a>
                            </li>
                            <li>
                                <a href="features.html#imagemanipulation">Image Manipulation</a>
                            </li>
                            <li>
                                <a href="features.html#_file_upload">File Upload</a>
                            </li>
                            <li>
                                <a href="features.html#multilanguage">Multi-Language</a>
                            </li>
                            <li>
                                <a href="features.html#_permissions">Permissions</a>
                            </li>
                            <li>
                                <a href="features.html#_versioning">Versioning</a>
                            </li>
                            <li>
                                <a href="features.html#_content_releases">Content Releases</a>
                            </li>
                            <li>
                                <a href="features.html#_search">Search</a>
                            </li>
                            <li>
                                <a href="features.html#_preview_handling">Preview Handling</a>
                            </li>
                            <li>
                                <a href="features.html#_password_recovery">Password Recovery</a>
                            </li>
                            <li>
                                <a href="features.html#_schema_microschema_migration">Schema &amp; Microschema Migration</a>
                            </li>
                            <li>
                                <a href="features.html#_eventbus_bridge_websocket">Eventbus Bridge &amp; Web Socket</a>
                            </li>
                            <li>
                                <a href="features.html#_clustering">Clustering</a>
                            </li>
                        </ul>
                    </li>
                    <li class="section">
                        <h2><a href="user-interface.html">User Interface</a></h2>
                        <ul>
                            <li>
                                <a href="user-interface.html#_creating_and_managing_content">Creating and Managing Content</a>
                            </li>
                            <li>
                                <a href="user-interface.html#_searching">Searching</a>
                            </li>
                            <li>
                                <a href="user-interface.html#_administrative_functions">Administrative Functions</a>
                            </li>
                            <li>
                                <a href="user-interface.html#_configuration">Configuration</a>
                            </li>                            
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="doc-toc">
                    <li class="section">
                        <h2><a href="references.html">References</a></h2>
                        <ul>
                            <li>
                                <a href="references.html">APIs</a>
                                <ul>
                                    <li>
                                        <a href="references.html#_rest_api">REST API</a>
                                    </li>
                                    <li>
                                        <a href="graphql.html">GraphQL</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="references.html#_http_details">HTTP Details</a>
                                <ul>
                                    <li>
                                        <a href="references.html#_http_details">Security/SSL</a>
                                    </li>
                                    <li>
                                        <a href="references.html#_encoding">Encoding</a>
                                    </li>
                                    <li>
                                        <a href="references.html#_headers">Headers</a>
                                    </li>
                                    <li>
                                        <a href="references.html#_cors">CORS</a>
                                    </li>
                                    <li>
                                        <a href="references.html#_etag_handling">ETag Handling</a>
                                    </li>
                                    <!--
                                    <li>
                                        <a href="references.html">Error Codes</a>
                                    </li>
                                    -->
                                </ul>
                            </li>
                            <li>
                                <a href="references.html#_authentication">Authentication</a>
                                <ul>
                                    <li>
                                        <a href="references.html#_overview">Overview</a>
                                    </li>
                                    <li>
                                        <a href="references.html#_login">Login</a>
                                    </li>
                                    <li>
                                        <a href="references.html#_api_token">API Token</a>
                                    </li>
                                    <li>
                                        <a href="references.html#_anonymous_access">Anonymous Access</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li class="section">
                        <h2><a href="platforms.html">Platforms</a></h2>
                        <ul>
                            <li>
                                <a href="platforms.html#_javascript">JavaScript</a>
                            </li>
                            <li>
                                <a href="platforms.html#_java">Java</a>
                            </li>
                            <li>
                                <a href="platforms.html#_go">Go</a>
                            </li>
                            <li>
                                <a href="platforms.html#_php">PHP</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
++++