= Gentics Mesh Documentation

:raml-json: ../raml/json

This documentation provides information on the structure and functionality of the Gentics Mesh server and its API endpoints.

== TL;DR

Gentics Mesh is a API-Centric CMS Server written in Java which enables you to store and retrieve JSON documents and binaries via REST.
Gentics Mesh will also provide you a lot of powerful tools build around and for those documents.

 * Document level permission system
 * Search API
 * link:graphql.html[GraphQL API]
 * Webroot API for easy integration with modern routing frameworks
 * Image Manipulation API
 * Tagging system
 * Schema system for documents
 * Clustering (in development)
 * Versioning of your documents

////////////////////
=== Examples

*Create a new node*

It is mandatory to specify the ```parentNode``` reference, ```language```  and ```schema``` field when creating a node. 
It is possible specify the schema uuid instead of the name. At least one property within the ```schema``` object must be set.

[source]
----
POST /api/v1/demo/nodes HTTP/1.1
Host: localhost:8080
Cookie: mesh.session=61ac7969-e5ad-4c28-bc0f-0869a04e4db1
Content-Type: application/json
Accept: application/json

include::examples/api/request/api/v1/\{project\}/nodes/request-body.json[]
----

*Update an existing node*

The created node can be updated via a ```PUT``` request. You may only include those field which should be updated.

[source]
----
PUT /api/v1/demo/nodes/5af8d0e077e34361b8d0e077e353619e HTTP/1.1
Host: localhost:8080
Cookie: mesh.session=61ac7969-e5ad-4c28-bc0f-0869a04e4db1
Content-Type: application/json
Accept: application/json

include::examples/api/request/api/v1/\{project\}/nodes/\{nodeUuid\}/request-body.json[]
----

*Add a tag to a node*

Tagging nodes requires just a simple ```PUT``` request.

[source]
----
PUT /api/v1/demo/nodes/5af8d0e077e34361b8d0e077e353619e/tags/ba2edcdb1234489daedcdb1234289d38 HTTP/1.1
Host: localhost:8080
Cookie: mesh.session=61ac7969-e5ad-4c28-bc0f-0869a04e4db1
Accept: application/json
----
////////////////////

== link:building-blocks.html[Building Blocks]
== link:features.html[Features]
== link:references.html[References]
== link:aministration-guide.html[Administration Guide]
== link:user-interface.html[Gentics Mesh User Interface]
== link:plattforms.html[Plattforms]
