:icons: font

= Performance Guide

This document contains useful information about performance related topics. 
It will help you make the right modeling choices when using Gentics Mesh.

It is possible to store 200.000 and more nodes within a single node container. 
We have made tests with more then 2.000.000 nodes in Gentics Mesh. 
When storing that amount of nodes you should keep the following design suggestions in mind:

== Paging

Regular paging performance will be impacted by the amount of nodes that are stored within a node container.
It is advised to use GraphQL when accessing nodes in this sitation. GraphQL will allow you to fine tune the paging information.

include::examples/graphql/node-light-paging-query[]

The paging performance can be greatly increased by omitting the *pageCount* and *totalCount* field.
Including these fields will require Gentics Mesh to check all elements for permissions in order to count them.

== Contents

If you plan to use a caching layer or rely on the browser caching of node requests you can use the link:references.html#_etag_handling[ETag] value to cache these contents.
In other cases it may be better to use the link:graphql.html[GraphQL] endpoint which allows you to only load specific data. 
GraphQL can possibly also be used to reduce the amount of requests which need to be invoked and thus increase your implementation performance.

